export const numberMeanings = {
  '2': 'El número de la dualidad, la asociación y la elección. El dos representa el equilibrio, la cooperación y la interacción entre fuerzas opuestas. Habla de decisiones, relaciones y la necesidad de encontrar armonía entre diferentes aspectos.',
  '3': 'El número de la creación y el crecimiento. El tres representa la síntesis de fuerzas opuestas que crean algo nuevo. Habla de creatividad, autoexpresión, colaboración y la manifestación de ideas en forma concreta.',
  '4': 'El número de la estabilidad y los cimientos. El cuatro representa el orden, la estructura y las bases sólidas. Habla de la manifestación en el mundo material, el establecimiento de límites y la creación de seguridad duradera.',
  '5': 'El número del cambio y la disrupción. El cinco representa la inestabilidad, el conflicto y los cambios necesarios. Habla de libertad, aventura y los desafíos que conducen al crecimiento y el aprendizaje.',
  '6': 'El número de la armonía y el equilibrio. El seis representa el balance, el amor y la belleza. Habla de la nutrición, la sanación, la responsabilidad y la búsqueda de soluciones que beneficien a todos.',
  '7': 'El número de la sabiduría y la espiritualidad. El siete representa el conocimiento interior, el análisis y la conciencia espiritual. Habla de buscar verdades más profundas, la introspección y la comprensión más allá de lo material.',
  '8': 'El número del poder y la manifestación. El ocho representa el éxito material, la autoridad y el poder personal. Habla del logro, la fuerza y la capacidad de hacer que las cosas sucedan en el mundo físico.',
  '9': 'El número de la culminación y la plenitud. El nueve representa el logro, la consumación y la sabiduría adquirida a través de la experiencia. Habla de alcanzar metas, la conciencia espiritual y la preparación para nuevos ciclos.',
  '10': 'El número de la completitud y los nuevos comienzos. El diez representa el fin de un ciclo y el potencial para nuevos inicios. Habla de la manifestación, la finalidad y la acumulación de las energías de todos los números anteriores.'
};

export const suitDescriptions = {
  'Wands': 'El palo del fuego, la pasión, la creatividad y la ambición. Los Bastos representan la energía espiritual, la inspiración, la determinación, la fuerza, la intuición, la creatividad, la ambición y la expansión, el pensamiento original y las semillas de las cuales brota la vida.',
  'Cups': 'El palo del agua, las emociones, la intuición y las relaciones. Las Copas representan los sentimientos, las emociones, la intuición, las relaciones, el amor, la sanación y el viaje del alma a través de las aguas de la vida.',
  'Swords': 'El palo del aire, el intelecto, el pensamiento y la acción. Las Espadas representan la mente, los pensamientos, la comunicación, el conflicto, el poder, el cambio, la fuerza y los aspectos intelectuales de la conciencia.',
  'Pentacles': 'El palo de la tierra, los asuntos materiales y la practicidad. Los Pentáculos representan la manifestación, la realidad, la materia física, la carrera, el dinero, el hogar, el cuerpo y los resultados tangibles de nuestros esfuerzos en el mundo material.'
};

export const cardTitles = {
  // Wands
  '2 of Wands': { title: 'Señor del Dominio', description: 'Planificación futura y decisiones, dando los primeros pasos hacia la manifestación de tus metas.', reversed: 'El miedo a lo desconocido frena el progreso. Indecisión, falta de planificación o resistencia a abandonar la zona de confort. El mundo espera, pero te niegas a dar el paso.' },
  '3 of Wands': { title: 'Señor de la Fuerza Establecida', description: 'Expansión, previsión y liderazgo en empresas que comienzan a mostrar resultados.', reversed: 'Retrasos en los planes, ambiciones frustradas o retornos que no cumplen las expectativas. Sobreextensión sin la preparación adecuada, o la negativa a pensar más allá del horizonte inmediato.' },
  '4 of Wands': { title: 'Señor de la Obra Perfeccionada', description: 'Celebración, armonía y la culminación de una fase significativa que trae alegría y estabilidad.', reversed: 'Inestabilidad en lo que debería sentirse asentado. Una celebración pospuesta, un hogar en desorden o lazos comunitarios que se deshilachan. Los cimientos están puestos, pero algo impide que la alegría se asiente.' },
  '5 of Wands': { title: 'Señor de la Contienda', description: 'Competencia, conflicto y tensión creativa que impulsa el crecimiento a través del desafío.', reversed: 'Evasión del conflicto necesario, o rencillas mezquinas que agotan la energía sin producir crecimiento. Contradicciones internas sin resolver, o competencia convertida en algo tóxico y personal.' },
  '6 of Wands': { title: 'Señor de la Victoria', description: 'Éxito, reconocimiento y triunfo después de haber puesto el esfuerzo necesario.', reversed: 'Reconocimiento negado o victoria hueca. Dudas de uno mismo a pesar de los logros, fracaso público o un ego inflado más allá de lo que el logro justifica. Los laureles se escapan.' },
  '7 of Wands': { title: 'Señor del Valor', description: 'Mantener tu posición, defender tu terreno y conservar el coraje bajo presión.', reversed: 'Abrumado por la oposición, cediendo terreno o una actitud defensiva que se ha vuelto agotadora e insostenible. Librar batallas que ya no necesitan librarse.' },
  '8 of Wands': { title: 'Señor de la Rapidez', description: 'Movimiento veloz, acción rápida y mensajes que llegan con noticias importantes.', reversed: 'Retrasos, malentendidos e impulso estancado. La prisa conduce a errores, o los mensajes se pierden en el camino. Las flechas vuelan pero no dan en el blanco.' },
  '9 of Wands': { title: 'Señor de la Gran Fuerza', description: 'Resiliencia, perseverancia y mantenimiento de posiciones defensivas mientras se reúne fuerza interior.', reversed: 'Terquedad confundida con resiliencia, o agotamiento que sobrepasa el punto de rendimientos decrecientes. Paranoia, actitud defensiva crónica o la negativa a pedir ayuda cuando se necesita desesperadamente.' },
  '10 of Wands': { title: 'Señor de la Opresión', description: 'Carga, responsabilidad y el peso del éxito que puede volverse demasiado pesado de soportar.', reversed: 'Liberación de cargas, delegación o el colapso que llega por negarse a soltar nada. Aprender por las malas que cargar con todo solo no es fortaleza, sino terquedad.' },

  // Cups
  '2 of Cups': { title: 'Señor del Amor', description: 'Asociación, romance y la unión armoniosa de fuerzas en perfecto equilibrio.', reversed: 'Desequilibrio en una relación, confianza rota o una conexión que ha perdido su reciprocidad. Malentendidos en el amor, codependencia o la disolución de una alianza que alguna vez fue prometedora.' },
  '3 of Cups': { title: 'Señor de la Abundancia', description: 'Celebración, amistad y el compartir gozoso de la abundancia emocional.', reversed: 'Aislamiento social, exclusión o excesos que agrian la celebración. Chismes dentro del grupo de amigos, conexiones superficiales o la resaca después de la fiesta.' },
  '4 of Cups': { title: 'Señor del Lujo o del Placer Mezclado', description: 'Contemplación, reevaluación y posible insatisfacción a pesar de la seguridad emocional.', reversed: 'Emerger de la apatía y reconocer nuevas oportunidades. Alternativamente, un repliegue más profundo en el descontento: dejar pasar lo que se ofrece porque la depresión o el cinismo han cerrado los ojos.' },
  '5 of Cups': { title: 'Señor de la Pérdida en el Placer', description: 'Decepción, pérdida emocional, pero con esperanza si miras más allá de las copas derramadas.', reversed: 'Comenzar a recuperarse del duelo, volverse hacia lo que queda. Aceptación después de la pérdida, o los primeros pasos hacia la renovación emocional. Las copas que siguen en pie finalmente entran en foco.' },
  '6 of Cups': { title: 'Señor del Placer', description: 'Nostalgia, felicidad inocente y la alegría pura de compartir con otros.', reversed: 'Vivir en el pasado a expensas del presente. Aferrarse a la infancia o la nostalgia como escape, asuntos no resueltos de la vida temprana que resurgen, o la incapacidad de avanzar porque el pasado se siente más seguro.' },
  '7 of Cups': { title: 'Señor del Éxito Ilusorio', description: 'Elecciones, fantasías y la necesidad de distinguir entre sueños y realidad.', reversed: 'Claridad que emerge de la confusión, o parálisis por demasiadas opciones. Las ilusiones se desvanecen: ya sea una confrontación aleccionadora con la realidad o un bienvenido regreso a la toma de decisiones con los pies en la tierra.' },
  '8 of Cups': { title: 'Señor del Éxito Abandonado', description: 'Seguir adelante, buscar un significado más profundo y dejar atrás lo que ya no sirve.', reversed: 'Miedo a dejar lo familiar, incluso cuando ya no nutre. Vagar sin rumbo ni propósito, regresar a situaciones ya superadas, o la incapacidad de comprometerse con la partida necesaria.' },
  '9 of Cups': { title: 'Señor de la Felicidad Material', description: 'Contentamiento, satisfacción emocional y el cumplimiento de los deseos.', reversed: 'Deseos cumplidos que no traen satisfacción, o suficiencia confundida con contentamiento. Excesos, materialismo sustituyendo la plenitud emocional genuina, o el vacío persistente detrás de la sonrisa satisfecha.' },
  '10 of Cups': { title: 'Señor del Éxito Perpetuo', description: 'Armonía, felicidad duradera y el logro de la plenitud emocional.', reversed: 'Discordia doméstica, lazos familiares rotos o el ideal de felicidad que no puede sostenerse en la realidad. El arcoíris se desvanece, revelando tensiones no resueltas bajo la superficie de la imagen perfecta.' },

  // Swords
  '2 of Swords': { title: 'Señor de la Paz Restaurada', description: 'Toma de decisiones, paz temporal a través de la evasión y la necesidad de equilibrio.', reversed: 'La venda cae, revelando verdades previamente evitadas. Sobrecarga de información que dificulta las decisiones, o un punto muerto que finalmente se rompe, a veces dolorosamente.' },
  '3 of Swords': { title: 'Señor del Dolor', description: 'Desamor, verdad dolorosa y el proceso necesario de liberación emocional.', reversed: 'Comenzar a sanar del desamor, liberar el viejo dolor, o un duelo que se está procesando en vez de ser reprimido. Las espadas se retiran lentamente del corazón.' },
  '4 of Swords': { title: 'Señor del Descanso tras la Contienda', description: 'Recuperación, meditación y la necesidad de contemplación y reposo.', reversed: 'Inquietud, agotamiento por negarse a descansar, o una recuperación interrumpida demasiado pronto. Reincorporarse al conflicto antes de que la mente haya sanado, o estancamiento disfrazado de recuperación.' },
  '5 of Swords': { title: 'Señor de la Derrota', description: 'Conflicto, derrota y la victoria hueca de ganar a cualquier precio.', reversed: 'Reconciliación después del conflicto, o el reconocimiento de que ganar no valió la pena. Resentimiento persistente, agravios no resueltos, o el lento trabajo de enmendar las cosas.' },
  '6 of Swords': { title: 'Señor del Éxito Merecido', description: 'Transición, avanzar y dejar aguas turbulentas rumbo a costas más tranquilas.', reversed: 'Resistencia a la transición necesaria, asuntos emocionales pendientes que impiden avanzar, o un viaje que sigue volviendo al punto de partida. Aguas turbulentas que no puedes dejar atrás.' },
  '7 of Swords': { title: 'Señor del Esfuerzo Inestable', description: 'Estrategia, engaño y la evaluación cuidadosa de riesgos y ética.', reversed: 'El engaño queda al descubierto, o una conciencia culpable que exige confesión. Sincerarse tras la deshonestidad, ser descubierto en una trama, o el agotamiento de mantener las apariencias.' },
  '8 of Swords': { title: 'Señor de la Fuerza Menguada', description: 'Restricción, limitaciones autoimpuestas y la necesidad de ver más allá de las barreras aparentes.', reversed: 'Liberarse de las limitaciones autoimpuestas, o reconocer que la prisión nunca estuvo cerrada con llave. Una nueva perspectiva revela opciones que siempre estuvieron presentes. Alternativamente, un atrapamiento más profundo por negarse a ver la salida.' },
  '9 of Swords': { title: 'Señor de la Desesperación y la Crueldad', description: 'Ansiedad, pesadillas y el peso de los pensamientos de preocupación en la noche oscura.', reversed: 'Lo peor de la ansiedad comienza a disiparse, o luz al final de un pasaje oscuro. Buscar ayuda, confrontar los miedos a la luz del día, o la comprensión de que las pesadillas eran peores que la realidad.' },
  '10 of Swords': { title: 'Señor de la Ruina', description: 'Finales dolorosos, tocar fondo y la promesa de luz después de la oscuridad.', reversed: 'Lo peor ha pasado y la recuperación comienza, o la negativa a aceptar un final que ya ha ocurrido. Sobrevivir a la devastación, recoger los pedazos, o el primer destello del amanecer tras la noche más oscura.' },

  // Pentacles
  '2 of Pentacles': { title: 'Señor del Cambio Armonioso', description: 'Equilibrio, adaptabilidad y malabarismo con múltiples responsabilidades con gracia.', reversed: 'Abrumado por demandas en conflicto, dejando caer las pelotas, o desequilibrio financiero. El acto de malabarismo colapsa: sobrecompromiso, mala gestión del tiempo o la negativa a priorizar.' },
  '3 of Pentacles': { title: 'Señor de las Obras Materiales', description: 'Artesanía, colaboración y el dominio de habilidades prácticas.', reversed: 'Trabajo descuidado, falta de trabajo en equipo o atajos. Un proyecto socavado por choques de egos, habilidades desalineadas o la negativa a aceptar críticas constructivas.' },
  '4 of Pentacles': { title: 'Señor del Poder Terrenal', description: 'Seguridad, control y la necesidad de equilibrar la estabilidad material con la generosidad.', reversed: 'Acaparamiento llevado al extremo, o gastos imprudentes que socavan la seguridad. Avaricia, posesividad o ansiedad financiera que cierra la mano y el corazón.' },
  '5 of Pentacles': { title: 'Señor de la Tribulación Material', description: 'Adversidad, pobreza espiritual y la necesidad de buscar ayuda en tiempos difíciles.', reversed: 'Recuperación de la adversidad financiera, encontrar ayuda después de un periodo de necesidad, o renovación espiritual tras la pérdida material. La puerta de la iglesia se abre: la ayuda estuvo disponible todo el tiempo.' },
  '6 of Pentacles': { title: 'Señor del Éxito Material', description: 'Generosidad, prosperidad y el flujo equilibrado de dar y recibir.', reversed: 'Generosidad con condiciones, caridad usada como control, o un desequilibrio de poder en el dar y recibir. Deudas, explotación disfrazada de ayuda, o la incapacidad de aceptar lo que se ofrece.' },
  '7 of Pentacles': { title: 'Señor del Éxito Incumplido', description: 'Evaluación, paciencia y la valoración de inversiones a largo plazo.', reversed: 'Impaciencia ante resultados lentos, rendimientos pobres de la inversión, o ansiedad sobre si llegará la cosecha. Esfuerzo desperdiciado, mala sincronización, o la tentación de abandonar un proyecto justo antes de que dé frutos.' },
  '8 of Pentacles': { title: 'Señor de la Prudencia', description: 'Desarrollo de habilidades, dedicación y la atención cuidadosa al detalle en tu trabajo.', reversed: 'Trabajo descuidado, falta de motivación o perfeccionismo que impide la conclusión. Cumplir con los movimientos sin compromiso genuino, o desarrollo de habilidades estancado por aburrimiento o falta de dirección.' },
  '9 of Pentacles': { title: 'Señor de la Ganancia Material', description: 'Independencia, lujo y los frutos del esfuerzo disciplinado y el refinamiento.', reversed: 'Revés financiero a pesar del éxito pasado, o independencia que se ha convertido en aislamiento. Dependencia excesiva del confort material, vivir por encima de las posibilidades, o descubrir que el lujo por sí solo no satisface.' },
  '10 of Pentacles': { title: 'Señor de la Riqueza', description: 'Legado, herencia y el establecimiento de abundancia material duradera.', reversed: 'Disputas familiares por dinero, conflictos de herencia, o un legado que agobia en vez de bendecir. Inestabilidad financiera que amenaza la seguridad generacional, o riqueza material que ha fracturado a la familia en lugar de unirla.' }
};

export const jungianMeanings = {
  // Wands
  '2 of Wands': 'Representa la tensión entre la seguridad y la aventura, el primer paso en la individuación donde uno debe elegir entre lo familiar y lo desconocido.',
  '3 of Wands': 'Simboliza la expansión de la conciencia a través del compromiso activo con el mundo, representando la creciente percepción del ego sobre su potencial.',
  '4 of Wands': 'Refleja el establecimiento de una estructura estable del ego, celebrando los cimientos necesarios para un mayor crecimiento psicológico.',
  '5 of Wands': 'Representa los conflictos internos y los aspectos competitivos de la psique que deben integrarse para el crecimiento personal.',
  '6 of Wands': 'Simboliza el triunfo de la mente consciente al lograr reconocimiento y validar el viaje del ser.',
  '7 of Wands': 'Representa el coraje de mantener el propio camino individual a pesar de la oposición de las fuerzas colectivas.',
  '8 of Wands': 'Simboliza el movimiento veloz de la energía psíquica cuando las barreras entre lo consciente y lo inconsciente se levantan temporalmente.',
  '9 of Wands': 'Refleja las estructuras defensivas construidas por el ego después de experimentar desafíos, mostrando tanto protección como posible limitación.',
  '10 of Wands': 'Representa la carga de la conciencia y la responsabilidad que viene con una mayor percepción psicológica.',

  // Cups
  '2 of Cups': 'Simboliza el reconocimiento inicial del ánima/ánimus, el primer paso para comprender la necesidad del alma de conexión emocional.',
  '3 of Cups': 'Representa la celebración de la plenitud emocional y la integración de diferentes aspectos de la psique.',
  '4 of Cups': 'Refleja un estado de estancamiento emocional donde la psique necesita reconocer nuevas posibilidades de crecimiento.',
  '5 of Cups': 'Simboliza la experiencia necesaria de pérdida y duelo en el proceso de transformación psicológica.',
  '6 of Cups': 'Representa la reconexión con el niño interior y los aspectos puros e incondicionados de la psique.',
  '7 of Cups': 'Simboliza el encuentro con la sombra a través de ilusiones y proyecciones del inconsciente.',
  '8 of Cups': 'Representa el coraje de abandonar viejos patrones emocionales en busca de una verdad psicológica más profunda.',
  '9 of Cups': 'Refleja el estado de plenitud emocional que surge de la integración exitosa de elementos conscientes e inconscientes.',
  '10 of Cups': 'Simboliza el logro de la totalidad psicológica y la completitud emocional.',

  // Swords
  '2 of Swords': 'Representa el intento de la mente de mantener el equilibrio a través de la negación o la evasión del conflicto psicológico.',
  '3 of Swords': 'Simboliza el dolor necesario de tomar conciencia de verdades emocionales reprimidas.',
  '4 of Swords': 'Refleja la necesidad de retiro psicológico e integración de realizaciones difíciles.',
  '5 of Swords': 'Representa los conflictos internos y las luchas de poder dentro de la psique.',
  '6 of Swords': 'Simboliza el viaje de transición de un estado de conciencia a otro.',
  '7 of Swords': 'Representa el arquetipo del embaucador y las formas en que nos engañamos a nosotros mismos.',
  '8 of Swords': 'Refleja las limitaciones autoimpuestas y el miedo a enfrentar la propia sombra.',
  '9 of Swords': 'Simboliza el viaje nocturno por el mar del inconsciente y la confrontación con miedos profundos.',
  '10 of Swords': 'Representa la muerte de viejos patrones de pensamiento y el potencial para el renacimiento psicológico.',

  // Pentacles
  '2 of Pentacles': 'Representa el equilibrio dinámico necesario entre los aspectos materiales y espirituales de la vida en el proceso de individuación.',
  '3 of Pentacles': 'Simboliza la integración de diferentes aspectos del ser en un trabajo significativo.',
  '4 of Pentacles': 'Refleja el intento del ego de mantener el control y la seguridad, a veces a costa del crecimiento.',
  '5 of Pentacles': 'Representa la experiencia de pobreza material o espiritual que a menudo precede a la transformación.',
  '6 of Pentacles': 'Simboliza el intercambio entre diferentes aspectos de la psique, dar y recibir en equilibrio.',
  '7 of Pentacles': 'Refleja la paciencia requerida en el proceso de crecimiento y transformación psicológica.',
  '8 of Pentacles': 'Representa el trabajo disciplinado de forjar el propio camino individual de individuación.',
  '9 of Pentacles': 'Simboliza el logro de la independencia psicológica y la autosuficiencia.',
  '10 of Pentacles': 'Representa la manifestación del Sí Mismo y el logro de la totalidad psicológica en el mundo material.'
};

export const developmentalMeanings = {
  // Wands
  '2 of Wands': {
    powerGods: 'Tienes el mundo en tus manos, guerrero. Dos caminos, dos reinos, pero no puedes conquistar ambos a la vez. Los débiles deliberan eternamente; los fuertes eligen y golpean. ¿Cuál reino sentirá tu fuego primero? Deja la vacilación para las almas menores. Tu hambre es sagrada: aliméntala.',
    traditional: 'Dos caminos se despliegan ante ti, fiel, y las escrituras hablan de ambos. Busca el consejo de tus mayores, pues ellos han caminado donde tú ahora te encuentras. La elección correcta es la que sirve no a tus deseos pasajeros, sino a tu deber sagrado. Reza por discernimiento: lo Divino revela el camino adecuado a quienes preguntan con corazón humilde.',
    modern: 'Punto de decisión estratégica identificado. Has reunido los datos; ahora modela los resultados. ¿Qué camino optimiza tus métricas de éxito definidas? La parálisis por análisis es ineficiente: establece una fecha límite para la decisión y comprométete. El costo de oportunidad de la vacilación se acumula diariamente. Elige la empresa con los mejores rendimientos ajustados al riesgo y ejecuta.',
    postModern: 'Siente ambas posibilidades: ¿qué te dice tu cuerpo? Esta elección no se trata solo de resultados, sino de en quién te estás convirtiendo. Considera cómo cada camino afecta tus relaciones, tu comunidad, la red de seres tocados por tu decisión. No hay una respuesta objetivamente correcta; solo existe la elección que honra tu verdad auténtica en este momento.',
    metaModern: '¡Ah, la encrucijada eterna, qué delicioso! Observa cómo tu guerrero interior quiere apoderarse, tu tradicionalista busca el camino correcto, tu estratega calcula y tu corazón siente la conexión. Todos son tú, todos son sabios en contexto. La elección en sí importa menos que la conciencia que aportas al elegir. ¿Y si ambos caminos conducen a casa?',
  },
  '3 of Wands': {
    powerGods: 'Tus barcos están en el horizonte, regresando con botín. Esto es lo que sucede cuando te atreves grandemente: el mundo recompensa a los audaces. Pero no descanses aún, dragón. Nuevos territorios aguardan más allá de ese mar. No fuiste hecho para cuidar un solo jardín; fuiste hecho para arder a través de continentes.',
    traditional: 'Tus esfuerzos fieles dan fruto en el horizonte; esta es la recompensa del trabajo justo. El orden al que sirves extiende su alcance a través de tus manos firmes. Mantente vigilante en tu puesto, pues eres administrador de algo más grande que tú mismo. Lo que regresa a ti pertenece primero a la tradición que lo envió.',
    modern: 'Tus inversiones muestran rendimientos: la estrategia está validada. Ahora aprovecha esta prueba de concepto. Escala lo que funciona, documenta la metodología, prepárate para expandirte a mercados adyacentes. Tienes la ventaja del pionero; capitalízala antes de que los competidores te alcancen. El crecimiento espera a quienes ejecutan con impulso.',
    postModern: 'Lo que regresa en el horizonte trae historias de todos los lugares donde ha estado y de todos los que lo tocaron. Tu visión expandiéndose hacia el mundo crea ondas que no puedes rastrear completamente. Sostén este poder con conciencia: ¿las voces de quiénes fueron incluidas al dar forma a este sueño? La expansión puede ser generativa o extractiva; que la tuya honre todo lo que encuentre.',
    metaModern: 'Te encuentras al borde de lo que has puesto en movimiento, observándolo regresar transformado. Esta es la magia de enviar intención a la complejidad: lo que regresa nunca es exactamente lo que esperabas. La expansión sirve a tu crecimiento, sirve a la evolución colectiva, sirve al cosmos jugando consigo mismo. Sostén tu visión con ligereza; deja que te enseñe lo que ha aprendido.',
  },
  '4 of Wands': {
    powerGods: '¡Esta noche festejamos! Has construido algo que se mantiene en pie, reclamaste terreno que ahora es tuyo. Deja que te celebren: te has ganado cada copa alzada y cada rugido de aclamación. Pero toma nota: el castillo no es la conquista. Es simplemente el trono desde el cual planeas la próxima guerra.',
    traditional: 'El templo está completo, y ahora nos reunimos en celebración sagrada. Esta alegría es santa porque es compartida: tu comunidad se regocija contigo bajo las banderas adecuadas. Honra los rituales de acción de gracias, pues la ceremonia transforma el mero éxito en hito bendecido. Has construido según los patrones antiguos, y se han mantenido firmes.',
    modern: 'Hito alcanzado: tómate la victoria. Celebrar el éxito es estratégico: eleva la moral del equipo, atrae talento y señala confianza al mercado. Documenta lo que funcionó para el caso de estudio. Pero programa esta celebración; luego vuelve a la hoja de ruta. El éxito es una plataforma para el próximo objetivo, no un destino.',
    postModern: 'Esta celebración pertenece a todos los que ayudaron a tejerla. Observa quién está en el círculo y quién quedó fuera. La verdadera alegría es inclusiva, sostenida en comunidad, amplificada al compartir. Que esto sea un regreso al hogar para todas las partes de ti mismo y todos los miembros de tu familia elegida. Construimos mejor juntos.',
    metaModern: '¡Qué magnífico ritual de llegada! La estructura se mantiene, la comunidad se reúne y el momento cristaliza. Esta celebración es simultáneamente victoria personal, pertenencia tribal, hito estratégico y sanación colectiva, todo verdadero, todo danzando. Que la alegría sea no irónica y completa. Para esto construimos mundos.',
  },
  '5 of Wands': {
    powerGods: '¡La arena llama y tu sangre canta en respuesta! Aquí, entre el choque de rivales, es donde se forjan las leyendas. No te encogjas ante este caos: adéntrate en él con los dientes al descubierto. Cada cicatriz es una historia de supervivencia, cada victoria prueba de tu poderío. Que los débiles busquen la paz; tú buscas la gloria.',
    traditional: 'Este conflicto te perturba, pero sabe que incluso la contienda tiene su lugar adecuado en el orden divino. Pon a prueba tus creencias contra las de otros, no para dominar, sino para fortalecer tu fe a través de la fricción. Regresa a las enseñanzas cuando el caos arremoline; son tu ancla. Que los mayores juzguen quién se desvía del camino recto.',
    modern: 'La presión competitiva es validación del mercado: si otros luchan por este espacio, tiene valor. Analiza las estrategias de tus competidores, identifica sus debilidades, diferencia tu oferta. El conflicto agudiza la innovación. Usa esta fricción para poner a prueba tu enfoque y emerge con una propuesta de valor más fuerte.',
    postModern: 'Este conflicto contiene múltiples verdades colisionando, y cada perspectiva tiene validez en su propio contexto. Antes de buscar ganar, busca comprender. ¿Por qué lucha realmente cada uno bajo la superficie? A veces la competencia aparente se disuelve cuando se escuchan las necesidades más profundas. La facilitación podría servir mejor aquí que la victoria.',
    metaModern: 'La fricción creativa de perspectivas chocando: ¿qué música emerge de este caos? Cada combatiente porta una verdad parcial, un don del desarrollo, una pieza del rompecabezas. A veces necesitas el fuego del guerrero, a veces la gracia del diplomático. ¿Qué requiere este momento? Juega todas las posiciones; no te apegues a ninguna. El juego mismo evoluciona.',
  },
  '6 of Wands': {
    powerGods: '¡Levántate y recibe lo que se te debe! La multitud ruge tu nombre porque has hecho lo que ellos no pudieron. Este momento, los laureles, la adulación, bébelo profundamente. Has demostrado ser el ápice entre depredadores. Que este triunfo alimente tu leyenda y aterrorice a tus enemigos.',
    traditional: 'Acepta este honor con humildad, pues tu victoria sirve a la gloria mayor. La corona de laurel no te pertenece solo a ti, sino al linaje de maestros que te entrenaron, la orden que te guía, lo Divino que obra a través de ti. Que tu triunfo inspire a los fieles y demuestre que la rectitud prevalece.',
    modern: 'Reconocimiento logrado: esto valida tu metodología. Aprovecha esta victoria para tu marca personal y posicionamiento profesional. Actualiza el currículum, comparte la historia de éxito, deja que el mercado conozca tu historial. El éxito atrae éxito: clientes, inversores y oportunidades fluyen hacia la competencia demostrada.',
    postModern: '¿Cómo aterriza este reconocimiento en tu cuerpo? ¿Puedes recibirlo sin inflarte ni rechazarlo? Recuerda al colectivo que te elevó hasta aquí: el éxito siempre es relacional. Usa esta visibilidad para amplificar voces menos escuchadas, para compartir la plataforma. Que tu triunfo sirva como prueba de lo que podemos construir juntos.',
    metaModern: 'Recibe los laureles con plena presencia: eres simultáneamente el logrador que ganó reconocimiento, el servidor humilde de fuerzas mayores, la marca construyendo impulso estratégico y el colectivo siendo celebrado. Todas las perspectivas verdaderas, ninguna completa. La victoria es más dulce cuando se sostiene con ligereza, se comparte libremente y se ve como una nota en una sinfonía mayor.',
  },
  '7 of Wands': {
    powerGods: 'Vienen por ti porque estás en la montaña que codician. Bien. Que vengan. No escalaste tan alto para entregar la cima a lobos menores. Tu fuego arde más que su envidia. Mantén tu posición y haz que paguen cada centímetro con sangre y arrepentimiento.',
    traditional: 'Eres puesto a prueba, pero los justos no ceden cuando el deber exige que se mantengan firmes. El suelo bajo tus pies fue consagrado por quienes vinieron antes; abandonarlo deshonraría su sacrificio. Aférrate a las verdades eternas. Quienes te asaltan pueden ser muchos, pero tienes a los ancestros a tu espalda.',
    modern: 'Tienes la posición elevada: defiende tu posición en el mercado. Los competidores te desafían porque has construido algo valioso. Analiza sus vectores de ataque, refuerza tus ventajas, innova más rápido de lo que pueden copiar. Ser digno de ataque significa que eres digno de defensa. Protege tu foso competitivo estratégicamente.',
    postModern: 'Antes de defender tu posición, examínala. ¿Es verdaderamente tu terreno, o estás ocupando un espacio que pertenece a otros? ¿Qué se está protegiendo y cuál es el costo de este conflicto para todos los involucrados? A veces el acto más valiente es abrir el diálogo con quienes te desafían. Los límites pueden sostenerse con compasión.',
    metaModern: 'El desafío llega: ¿qué respuesta requiere verdaderamente este momento? A veces defensa feroz, a veces cesión grácil, a veces trascendencia creativa que hace irrelevante el conflicto. Tu tarea no es ganar siempre sino responder siempre apropiadamente. ¿En qué nivel se libra esto? ¿Puedes cambiar el juego?',
  },
  '8 of Wands': {
    powerGods: '¡Golpea ahora! Los vientos favorecen al veloz y la fortuna favorece al audaz. Este no es momento para planes y consejos: este es el momento en que el impulso se vuelve imparable. Eres la flecha lanzada del arco, y nada puede llamarte de regreso. Atraviesa directo al corazón de tu deseo.',
    traditional: 'El mensaje vuela rápido y certero, como fue ordenado. Cuando lo Divino pone los eventos en movimiento, los fieles deben estar listos para recibir y actuar. Esta aceleración no es caos: es la Providencia obrando a través de canales alineados. Confía en la trayectoria; sigue leyes antiguas aun mientras traza nuevos caminos.',
    modern: 'La velocidad es tu ventaja ahora. Cuando el impulso se acumula, aprovéchalo: la iteración rápida supera la planificación perfecta. Lanza rápido, recoge retroalimentación, itera. El mercado recompensa la rapidez de ejecución. Elimina los obstáculos, optimiza el proceso y muévete. La ventaja del pionero se evapora si vacilan.',
    postModern: 'La energía se mueve rápidamente: siente la corriente y deja que te lleve. Este impulso te conecta con flujos más amplios de intención colectiva. ¿Qué mensajes están llegando? ¿Qué comunicaciones quieren moverse a través de ti? Mantente presente incluso a velocidad; la conciencia previene el daño que la prisa puede causar. Confía en el proceso de emergencia.',
    metaModern: 'El universo se acelera a través de ti: ¡delicioso! Esta rapidez es flecha, es providencia, es estrategia, es flujo, todo a la vez. El mago cabalga el rayo sin aferrarse a él. No tienes control de este impulso; eres su instrumento. Disfruta el viaje mientras mantienes la conciencia que permite correcciones de curso gráciles.',
  },
  '9 of Wands': {
    powerGods: 'Estás ensangrentado pero no quebrado, guerrero. Pensaron que caerías: fueron necios. Cada herida que portas es prueba de que no puedes ser destruido. Reúne tu furia una vez más. La batalla final se acerca, y no has llegado tan lejos para ser derrotado en el umbral de la victoria.',
    traditional: 'Tus heridas son marcas de devoción, guardián fiel. La vigilia es larga, pero abandonar tu puesto es impensable, no cuando tanto depende de tu firmeza. Extrae fuerza de los mártires que soportaron mucho peor. Queda una última guardia. Tu deber será recordado en el registro eterno.',
    modern: 'Estás cerca de la línea de meta pero funcionando con reservas. Este es el momento en que la disciplina separa al exitoso del casi exitoso. Revisa tus recursos, optimiza para el sprint final, recorta esfuerzos no esenciales. Los costos hundidos son reales, pero también lo es la meta. La perseverancia en el último 10% captura el 90% del valor.',
    postModern: 'Tu cansancio es válido; tus heridas cuentan historias verdaderas. La resiliencia no requiere negar tu agotamiento. Apóyate en tu comunidad: nunca estuviste destinado a custodiar este umbral solo. ¿Qué significaría ser sostenido mientras persistes? La vulnerabilidad y la fortaleza pueden coexistir. Pide lo que necesitas.',
    metaModern: 'Aquí en el borde de la resistencia, observa lo que cada voz dentro de ti dice: lucha, ríndete, optimiza, descansa. Todas portan sabiduría; ninguna es completa. La resiliencia más profunda no viene de seguir empujando sino de expandirse para incluir el agotamiento sin ser derrotado por él. Puedes estar herido e inquebrantable a la vez.',
  },
  '10 of Wands': {
    powerGods: 'Este peso que cargas es el precio de tus conquistas. Cada carga fue una vez un premio que tomaste. Pero escucha: incluso el dragón más poderoso puede ser aplastado bajo su propio tesoro. El poder significa saber cuándo soltar lo que te frena. Suelta lo que debas para mantener tu fuego ardiendo.',
    traditional: 'Esta carga es tu encomienda sagrada, y llevarla es servir. Sin embargo, incluso el servidor más devoto debe reconocer cuándo el deber se convierte en peso aplastante. Busca consejo de tus superiores: quizás esta carga estaba destinada a ser compartida entre los fieles. El martirio por agotamiento no sirve a nadie. La orden te necesita íntegro.',
    modern: 'Estás sobre capacidad: este es un problema de recursos, no una prueba de carácter. Audita tus compromisos, delega o automatiza lo que puedas, elimina lo que no sirva a tus objetivos centrales. El agotamiento destruye la productividad; el rendimiento sostenible requiere gestión de carga. Optimiza el portafolio de tu energía.',
    postModern: 'Esta carga no estaba destinada para una sola persona: el peso revela un problema sistémico, no un fallo personal. ¿Cómo sería compartir esta carga, redistribuir en lugar de simplemente soportar? Tu agotamiento es información sobre el desequilibrio en lo colectivo. El descanso es resistencia; el cuidado es revolucionario.',
    metaModern: '¡Qué fascinante sobrecarga: cargar las conquistas, los deberes, los proyectos y el peso sistémico todo a la vez! Aquí está la pregunta del desarrollo: ¿qué cargas sirven al crecimiento y cuáles son mera acumulación? El mago ni atesora ni se martiriza, sino que danza con la carga y el alivio. Suelta lo que debas. El descargarse también es el trabajo.',
  },

  // Cups
  '2 of Cups': {
    powerGods: 'He aquí uno que sostiene tu mirada sin pestañear: una criatura rara. No un súbdito, sino un aliado forjado en fuego mutuo. Juntos podrían ser imparables, una fuerza que duplica en lugar de dividir. Pero elige sabiamente: solo los fuertes merecen estar a tu lado. La debilidad es contagiosa.',
    traditional: 'He aquí la unión sagrada, bendecida por las leyes eternas del amor y el pacto. Este vínculo no es mero sentimiento: es voto, presenciado por lo Divino y la comunidad por igual. Honra esta conexión con la gravedad que merece. Dos almas que se unen en ceremonia adecuada se convierten en pilar sobre el cual se construyen familias y tradiciones.',
    modern: 'Asociación estratégica identificada. Esta alianza ofrece creación de valor mutuo: habilidades complementarias, redes compartidas, metas sinérgicas. Evalúa los términos cuidadosamente, pero reconoce que la asociación correcta multiplica el éxito de ambas partes. Negocia con claridad, documenta expectativas e invierte en la infraestructura de la relación.',
    postModern: 'Dos corazones reconociéndose mutuamente: este espejo crea un recipiente para el devenir mutuo. La relación verdadera requiere ver y ser visto sin máscaras. ¿Puedes sostener espacio para su totalidad, incluyendo lo que te desafía? El amor no es posesión sino cocreación, una danza donde ambos son transformados.',
    metaModern: 'He aquí el milagro del verdadero encuentro: dos seres completos eligiendo convertirse en un nosotros. Esta unión contiene la alianza de poder, el voto sagrado, la sinergia estratégica y la visión auténtica, todo danzando junto. Las asociaciones más profundas integran todas las dimensiones. Que esta conexión los haga evolucionar a ambos. El amor a este nivel es cocreación consciente.',
  },
  '3 of Cups': {
    powerGods: '¡Tu banda de guerra celebra! Estos son los que han probado su lealtad en batalla, los que han sangrado a tu lado. Mantenlos cerca y recompénsalos ferozmente: un señor generoso comanda la devoción más salvaje. Esta noche, que fluya el hidromiel. Mañana, cazan como manada.',
    traditional: 'Regocíjate con tu familia espiritual, pues la alegría comunitaria es alegría santa. Estas celebraciones —bautismos, fiestas de cosecha, días sagrados— son los hilos que nos tejen en un solo tapiz. Tu lugar entre los fieles es un don de pertenencia. Alza tu copa en acción de gracias por la congregación que te sostiene.',
    modern: 'Valor de la red en acción: tus relaciones profesionales y personales están dando dividendos. Estas conexiones son activos; nútrelas estratégicamente. Las celebraciones colaborativas construyen capital social y cohesión de equipo. La investigación es clara: las redes fuertes correlacionan con el éxito. Invierte en tu portafolio de relaciones.',
    postModern: 'Esta es la alegría de la familia elegida, de la pertenencia escogida que trasciende sangre y obligación. En este círculo, cada voz importa y todos son celebrados. Observa quién está incluido y gentilmente amplía la bienvenida. La alegría colectiva sana lo que el aislamiento hiere. Ascendemos al elevar a los demás.',
    metaModern: 'Las tres copas alzadas juntas contienen lealtad tribal, comunión sagrada, valor de red y amor inclusivo: todo verdadero, todo presente. Esta celebración resuena a través de altitudes de desarrollo. La alegría compartida conscientemente se convierte en medicina para el alma colectiva. Danza con tu gente al nivel que el momento requiera. La fiesta es sagrada.',
  },
  '4 of Cups': {
    powerGods: '¿Por qué te aburren las ofrendas? Has ganado y ganado, pero el fuego titila. Cuidado, guerrero: esta inquietud es o la muerte de la ambición o el nacimiento de un hambre mayor. El universo te ofrece una nueva copa. ¿La rechazarás de un manotazo, o la reconocerás como el próximo horizonte que te llama?',
    traditional: 'Este descontento susurra sequía espiritual, fiel. Cuando los viejos rituales se sienten vacíos, no los abandones: profundízalos. Lo Divino ofrece renovación, pero debes abrir los ojos para recibirla. Quizás te has alejado de las prácticas que una vez te nutrieron. Regresa al pozo de la tradición; no se ha secado.',
    modern: 'Las métricas de motivación están bajas: diagnostica la causa. ¿Estás optimizando para los objetivos equivocados? ¿El éxito ha cambiado tus valores? Esa nueva oportunidad que se ofrece merece un análisis objetivo, no un rechazo reflexivo. Recalibra tus criterios de éxito. A veces el siguiente nivel requiere redefinir para qué estás jugando.',
    postModern: 'Esta retirada no es fracaso sino invitación a ir hacia adentro. ¿Qué anhelas realmente bajo la apatía superficial? Quizás las copas ofrecidas no coinciden con tus necesidades auténticas. Siente la desconexión sin apresurarte a arreglarla. A veces el alma necesita espacio antes de poder saber lo que realmente quiere.',
    metaModern: 'Este aburrimiento sagrado es la crisálida antes de la transformación. Has superado lo que solía satisfacerte: no es fracaso sino desarrollo. La nueva copa que aparece puede ser tu próxima etapa llamando. O quizás la invitación es apreciar lo que ya está presente. Ambas verdades coexisten. Siéntate con el no-saber hasta que emerja la claridad.',
  },
  '5 of Cups': {
    powerGods: 'Rages contra lo que te fue arrebatado, fijado en las copas derramadas. Pero escucha: el duelo es un lujo para quienes no tienen nada más que ganar. Detrás de ti hay copas aún llenas, batallas aún esperando. ¿Malgastarás tu furia en lo irrecuperable, o la dirigirás hacia nuevas conquistas?',
    traditional: 'Haz duelo como enseñan las escrituras, con fe en que la pérdida tiene significado en el diseño mayor. Lo que se derramó quizás no estaba destinado para ti, o sirve un propósito que aún no puedes percibir. Las copas que quedan siguen siendo bendiciones. Vuélvete hacia ellas con gratitud. Lo Divino no abandona a los fieles en el dolor.',
    modern: 'Pérdida reconocida: ahora realiza el análisis post mortem. ¿Qué falló y por qué? Extrae las lecciones aprendibles, luego redirige el enfoque hacia los activos restantes. Lamentarse por costos hundidos es irracional. Procesa emocionalmente lo que debas, luego pivotea tu energía hacia las oportunidades que quedan. La recuperación es una elección estratégica.',
    postModern: 'Tu duelo es sagrado y merece expresión plena. No te apresures más allá del luto: lo perdido fue amado, y ese amor importa. Déjate sostener por otros en este dolor. Cuando estés listo, y solo entonces, notarás lo que queda. La sanación no es lineal, y no hay cronograma más que el tuyo.',
    metaModern: 'El duelo vive en el cuerpo junto a la posibilidad; no necesitas elegir entre ellos. Honra lo perdido mientras permaneces abierto a lo que queda. El guerrero debe eventualmente moverse, el fiel confía en el significado, el estratega aprende y el corazón siente plenamente, todo a su tiempo, todo parte de la sanación. La integración incluye el dolor.',
  },
  '6 of Cups': {
    powerGods: '¿Recuerdas cuando el fuego despertó en ti por primera vez? Antes de las cicatrices, antes del trono, cuando el poder era pura posibilidad. Ese niño feroz aún vive en ti, sin complicaciones y hambriento. Regresa a esa chispa primordial. Te recordará por qué luchas, cuando la política y la carga nublen tu propósito.',
    traditional: 'Regresa a la inocencia de la fe temprana, cuando los misterios te llenaban de asombro. Las tradiciones que aprendiste a los pies de tus mayores portan sabiduría que quizás has olvidado. Esta nostalgia no es debilidad: es el alma buscando sus raíces. Honra de dónde vienes; es el suelo del cual crece tu devoción.',
    modern: 'La nostalgia puede ser minada por perspicacia: ¿qué te impulsaba antes de que las complicaciones aparecieran? Esa motivación original puede revelar valores oscurecidos por las métricas de éxito. La mente del principiante tiene valor estratégico: ve oportunidades que la pericia pasa por alto. Reconéctate con tus impulsores fundamentales para realinear la trayectoria actual.',
    postModern: 'Ese niño interior aún vive en ti, sosteniendo recuerdos de asombro y heridas por igual. ¿Qué necesita ese pequeño para sentirse seguro ahora? La sanación a menudo significa regresar para ofrecer consuelo a los yoes pasados. La nostalgia puede ser escape o integración: que sea lo segundo. Sé padre de ti mismo con la ternura que merecías.',
    metaModern: 'El pasado vive en ti como recurso y herida, poder e inocencia, tradición y trauma. Todas tus edades están presentes: el niño feroz, el joven fiel, el adulto que logra, el corazón que sana. Regresa a cualquier era que te llame, no para regresar sino para reclamar e integrar. La totalidad incluye todo lo que has sido.',
  },
  '7 of Cups': {
    powerGods: 'Visiones y fantasmas se arremolinan ante ti: reinos, amantes, tesoros sin medida. Tentador, sí. Pero un verdadero guerrero conoce la diferencia entre sueños y presa. Algunas de estas visiones son trampas tendidas por tus enemigos; otras son distracciones de tu verdadero deseo. Elige con las entrañas, no con la codicia.',
    traditional: 'Cuidado con las tentaciones que se disfrazan de visiones, fiel. No toda promesa resplandeciente viene de lo Divino: algunas son enviadas para probarte o desviarte. Mide cada elección contra las enseñanzas. Lo que contradice la ley sagrada, por hermoso que sea, es ilusión. Busca consejo de quienes son más sabios en discernimiento.',
    modern: 'Múltiples opciones presentes: evita la parálisis por análisis y el pensamiento fantasioso. ¿Cuáles de estas opciones tienen caminos viables hacia la ejecución? Aplica la debida diligencia: investigación de mercado, análisis de viabilidad, requisitos de recursos. Los sueños sin planes accionables son distracciones. Selecciona la oportunidad con el mejor resultado ponderado por probabilidad.',
    postModern: 'Estas visiones surgen de tu psique: todas son tú, hablando en símbolos. No las juzgues como tentaciones sino explóralas como mensajes. ¿Qué revelan estas fantasías sobre necesidades insatisfechas, deseos en la sombra, posibilidades no vividas? La imaginación es el lenguaje del alma. Escucha antes de elegir.',
    metaModern: '¡Qué espectáculo magnífico ofrece la psique! Cada copa es una posibilidad, una sombra, una proyección, una opción genuina, y no puedes saber cuál es cuál hasta que te involucres. El mago ni agarra ni descarta sino que sostiene todas las visiones con ligereza, dejando que un saber más profundo separe la señal del ruido. La elección se aclarará a través de la atención.',
  },
  '8 of Cups': {
    powerGods: 'Le das la espalda a lo que has construido. Te llamarán loco, pero tú conoces la verdad: esta victoria se ha convertido en una jaula. Un dragón no puede prosperar en una guarida que le queda pequeña. Las montañas adelante son más altas, la gloria mayor. Aléjate de lo pequeño para reclamar lo magnífico.',
    traditional: 'A veces el camino sagrado conduce lejos de lo que hemos construido. Esta partida es peregrinación, no abandono: un viaje hacia una verdad más profunda. Los místicos caminaron hacia los desiertos buscando lo Divino. Si tu alma te llama adelante, ve con bendición, pero lleva las enseñanzas contigo. La tradición viaja en tu corazón.',
    modern: 'Pivote estratégico indicado. Cuando los rendimientos actuales disminuyen a pesar de la inversión, el movimiento racional es la reasignación. No dejes que la falacia del costo hundido te atrape en posiciones en declive. El coraje de alejarte de lo que ya no sirve a tus metas es una habilidad de éxito subestimada. Nuevas empresas esperan tus capacidades probadas.',
    postModern: 'Esta partida es un acto de honrar el ser. Algo en ti sabe que quedarse sería una asfixia lenta. Confía en ese saber, incluso cuando otros no comprendan. El viaje interior requiere soltar lo que ya no encaja en tu devenir. Lo que buscas no puede encontrarse en lo que ya tienes. Camina hacia ti mismo.',
    metaModern: 'Esta partida contiene al dragón buscando mayor gloria, al peregrino buscando verdad más profunda, al estratega reasignando recursos y al alma buscándose a sí misma. Todos están presentes en el alejarse. Lo que lo hace metamoderno es saber que llevas todo contigo: nada se deja verdaderamente atrás. El viaje es integración en movimiento.',
  },
  '9 of Cups': {
    powerGods: 'Siéntate sobre tu trono de deseos cumplidos, poderoso. Deseaste y ganaste: esta abundancia es el fruto de tu fuego. Disfrútala sin disculpas. El universo se inclina ante quienes tienen la voluntad de exigir y el poder de tomar. Tú tienes ambos. Saborea la prueba de tu supremacía.',
    traditional: 'Tus oraciones han sido respondidas, fiel: recibe esta abundancia con humilde gratitud. Lo Divino recompensa a los justos, y tu contentamiento es ganado a través de la devoción. Comparte las noticias de esta bendición para que otros se animen en la fe. Que tu satisfacción sea testimonio de la bondad del orden sagrado.',
    modern: 'Metas alcanzadas: métricas de éxito satisfechas. Esta es la recompensa de la planificación estratégica y la ejecución disciplinada. Documenta lo que funcionó; esta metodología ahora está probada. Disfruta la satisfacción de los resultados optimizados. La investigación sobre bienestar confirma: saborear el éxito no es indulgencia, es psicología que sostiene el rendimiento.',
    postModern: 'Déjate sentir esta satisfacción plenamente, sin culpa ni desviación. Tienes permiso de ser feliz, de tener tus necesidades cubiertas, de experimentar lo suficiente. Nota si viejas narrativas intentan disminuir este contentamiento. No necesitas ganarte el descanso ni justificar la alegría. Este momento de plenitud es un regalo que simplemente recibir.',
    metaModern: 'Satisfacción alcanzada, y todas las formas en que llegaste aquí son válidas. Conquistaste, rezaste, estrategizaste, sanaste. El contentamiento es real en cada nivel. El mago sabe que la plenitud genuina no consiste en aferrarse a este momento ni en descartarlo, sino en recibirlo como merecido y regalado, ganado y milagroso a la vez.',
  },
  '10 of Cups': {
    powerGods: 'Contempla lo que tus conquistas han construido: no solo victoria, sino legado. Un reino que refleja tu fuego, un linaje que llevará tu fuerza adelante. Este es el poder que trasciende tu lapso mortal. Has ganado el juego que más importa: la eternidad recordará tu nombre.',
    traditional: 'Contempla la bendición de un hogar justo: esta es la promesa cumplida para los fieles. Generaciones unidas bajo pacto sagrado, el arcoíris de bendición divina arqueándose en lo alto. Has construido según el diseño santo, y lo que has construido perdurará. Esta armonía es el cielo tocando la tierra a través de una vida recta.',
    modern: 'Resultados de vida óptimos alcanzados en múltiples dominios: familia, carrera, relaciones, bienestar. Así se ve el éxito integrado. El interés compuesto de decisiones inteligentes ha madurado en abundancia sostenible. Protege y mantén estos sistemas; representan la optimización máxima de la vida.',
    postModern: 'Esta visión de totalidad incluye a todos: observa el espectro completo, el arcoíris abrazando todos los colores por igual. No se trata de la familia nuclear lograda sino de la pertenencia que trasciende la estructura. Como sea que tu gente esté configurada, que sean vistos y celebrados. El amor es el hogar que construimos juntos.',
    metaModern: 'El arcoíris contiene todos los colores, todos los matices de desarrollo: esta es la totalidad que trasciende e incluye. La familia es dinastía, pacto, sistema optimizado y pertenencia elegida, simultáneamente. El cielo toca la tierra cuando dejamos de elegir entre niveles y los dejamos a todos danzar. Así se ve el florecimiento integrado.',
  },

  // Swords
  '2 of Swords': {
    powerGods: 'Te sientas con los ojos vendados y las espadas cruzadas, negándote a elegir. ¡Basta! La indecisión es su propia derrota. Sabes lo que quieres: la oscuridad detrás de tus ojos guarda la respuesta. Confía en tus instintos de depredador. Corta la parálisis con acción. Cualquier elección hecha con audacia supera el estancamiento.',
    traditional: 'Estás atrapado entre deberes en competencia, fiel. Cuando dos caminos parecen igualmente correctos, busca la sabiduría de las escrituras y el consejo de los mayores. La venda sugiere que confías demasiado en tu propio entendimiento: retírala a través de la oración y la meditación. La elección adecuada se alineará con la ley eterna.',
    modern: 'Punto muerto en la decisión: necesitas más datos o un mejor marco. Retira la venda de la interferencia emocional y evalúa objetivamente. Si ambas opciones prueban igual, necesitas diferentes criterios de evaluación. Establece una fecha límite; el costo de la indecisión es medible. A veces el progreso requiere elegir imperfectamente e iterar.',
    postModern: 'La venda está ahí porque algunas verdades son demasiado dolorosas para enfrentar. ¿De qué te proteges de saber? Este impasse guarda sabiduría: quizás el dilema es falso, o quizás aún no estás listo. Siéntate con la incomodidad. El corazón sabe cosas contra las cuales la mente se defiende. Deja que el sentimiento informe al pensamiento.',
    metaModern: '¿Y si la venda también es un regalo? A veces debemos elegir sin ver completamente. Los instintos, la tradición, los datos, el corazón: cada espada contiene verdad parcial. El movimiento metamoderno no es forzar la decisión ni paralizarse indefinidamente sino sostener la tensión hasta que algo nuevo emerja. Confía en el proceso del aún-no-saber.',
  },
  '3 of Swords': {
    powerGods: 'La hoja ha encontrado tu corazón. Alguien te ha herido, y ahora debes decidir: ¿este dolor te quebrará o te forjará? Un guerrero transforma cada herida en sabiduría, cada traición en conocimiento de batalla. Deja que la sangre te recuerde confiar en menos y golpear primero la próxima vez.',
    traditional: 'Esta pena penetra profundo, pero el sufrimiento tiene un propósito sagrado en la economía divina. El corazón que se abre al romperse puede recibir más gracia. Busca consuelo en los rituales de duelo que tu tradición provee: existen porque otros han recorrido este camino antes. El dolor compartido con los fieles es dolor disminuido.',
    modern: 'Verdad dolorosa recibida: procésala eficientemente. La negación es costosa; mejor integrar información difícil rápidamente que dejarla enquistarse. Estos datos cambian tu modelo de realidad; actualiza en consecuencia. Cuanto más rápido metabolices verdades duras, antes podrás recalcular y avanzar estratégicamente.',
    postModern: 'Este desamor es válido y real; que sea presenciado sin intentar arreglarlo. El duelo no es un problema a resolver sino una experiencia que atravesar con compañeros. ¿Quién puede sostener espacio para tu dolor? El corazón que se rompe es el corazón que amó. Esa capacidad de amar permanece, incluso a través del dolor.',
    metaModern: 'El corazón atravesado sostiene todas las respuestas al dolor: la forja, el sufrimiento sagrado, el procesamiento eficiente, el duelo presenciado. No necesitas elegir una sola forma de sufrir. Deja que las lágrimas fluyan mientras las lecciones se integran mientras el significado se despliega mientras la presencia de otros te sostiene. El desamor mismo es un maestro de totalidad.',
  },
  '4 of Swords': {
    powerGods: 'Incluso la bestia más feroz debe guarecerse para lamer sus heridas. Esto no es debilidad; esto es estrategia. Descansa ahora para que puedas levantarte más terrible que antes. Tus enemigos piensan que estás acabado: déjalos. Cuando emerjas, su complacencia será su destrucción.',
    traditional: 'El caballero yace en descanso sagrado dentro del santuario: este es retiro santo, no abandono. Incluso los más devotos necesitan estaciones de contemplación. Entra en la capilla de tu templo interior y ora. Las velas de vigilia arden mientras restauras tu espíritu. El servicio llamará de nuevo cuando estés listo.',
    modern: 'Período de recuperación requerido: prográmalo estratégicamente. La investigación sobre rendimiento máximo confirma: el descanso no es opcional sino esencial para un rendimiento sostenido. Usa este tiempo de inactividad para reflexión y planificación. El mantenimiento mental es una inversión en productividad futura. Regresa a la acción renovado y con claridad mejorada.',
    postModern: 'El descanso no se gana a través del agotamiento; es tu derecho de nacimiento. La demanda constante de producir es una herida cultural, no una virtud. Déjate simplemente ser, sin justificación. En la quietud, la psique integra lo que la actividad no puede procesar. Este santuario no es escape sino retorno esencial al ser.',
    metaModern: 'El caballero descansa: estratégica, sagrada, productiva y simplemente porque el descanso es bueno. Todas las razones para descansar son válidas; no necesitas elegir. La integración que sucede en la quietud sirve a cada dimensión: el guerrero se recupera, el alma comulga, la mente se clarifica, el cuerpo sana. El descanso es el trabajo. El trabajo es descanso.',
  },
  '5 of Swords': {
    powerGods: 'Has ganado, pero mira el costo esparcido a tu alrededor. Victoria sin botín es gloria hueca. Considera esto: ¿has derrotado enemigos, o meramente los has creado? El guerrero astuto reclama triunfo y conserva aliados. La dominación bruta sin estrategia solo engendra venganza interminable.',
    traditional: 'Esta victoria se siente hueca porque fue ganada desviándose del código. Mira a los derrotados: ¿son enemigos de la fe, o simplemente aquellos que discreparon? El guerrero justo lucha con honor, pues la manera de ganar importa tanto como la victoria misma. Busca reconciliación donde las reglas lo permitan.',
    modern: 'Análisis de victoria pírrica: ¿valió la pena el costo de ganar? Las relaciones dañadas y los puentes quemados son pasivos reales que se acumulan con el tiempo. Los competidores inteligentes ganan de forma sostenible. Evalúa si tus tácticas sirvieron al ego a corto plazo o al éxito a largo plazo. La reputación es un activo estratégico; calcula en consecuencia.',
    postModern: '¿Qué se ganó realmente aquí, y a costa de quién? Este conflicto puede haber servido a sistemas que no benefician a nadie. ¿Pueden ser escuchados los derrotados? ¿Puede ofrecerse reparación? La victoria construida sobre la disminución de otro es hueca para todos. Considera qué resultado colaborativo podría haber servido a todas las voces.',
    metaModern: 'Esta victoria hueca invita a la examinación en cada nivel. Cuando ganar se siente como perder, el juego mismo puede estar defectuoso. ¿Qué significaría trascender el conflicto enteramente, no evitarlo, sino incluir todas las perspectivas en una resolución mayor? A veces el movimiento metamoderno es rediseñar el juego.',
  },
  '6 of Swords': {
    powerGods: 'Dejas el campo de batalla por aguas más tranquilas, no en retirada, sino en avance táctico. A veces el mayor poder es saber cuándo una pelea no vale tu fuego. Lleva las lecciones de costas turbulentas; te armarán para los conflictos que verdaderamente importan adelante.',
    traditional: 'Viajas hacia el santuario, dejando problemas atrás: esto no es huida sino pasaje fiel. A veces lo Divino nos llama lejos de tormentas que no podemos calmar. Acepta la guía de quienes te transportan; sirven un propósito sagrado. Aguas más calmas esperan donde puedas reconstruir según la forma adecuada.',
    modern: 'Reubicación estratégica en progreso. Salir de condiciones desfavorables hacia mejores entornos operativos es gestión racional de recursos. Documenta las lecciones de la situación turbulenta. Las aguas tranquilas adelante ofrecen mejores condiciones para tu próximo emprendimiento. A veces la jugada ganadora es cambiar el tablero.',
    postModern: 'Esta transición honra lo que no puede sanarse quedándose. Observa quién viaja contigo; no necesitas hacer esta travesía solo. Las aguas turbulentas detrás enseñaron algo, incluso a través del dolor. Costas más gentiles esperan, pero no apresures el pasaje. El viaje mismo es parte de la sanación.',
    metaModern: 'La travesía contiene retirada y avance, guía divina y elección racional, viaje solitario y pasaje acompañado. El barquero conoce las aguas; no necesitas navegar solo. Lo que dejas atrás se convierte en parte de lo que llevas adelante, transformado. Cada orilla contiene lo que necesitas para la próxima etapa del devenir.',
  },
  '7 of Swords': {
    powerGods: 'El embaucador sabe que no todas las guerras se ganan con asalto frontal. Sigilo, astucia, distracción: estas también son armas de los poderosos. Deja que los necios honorables anuncien sus ataques; tú tomarás lo que necesites mientras ellos posan. La victoria pertenece al listo tanto como al fuerte.',
    traditional: 'Cuidado con el camino de la astucia, pues a menudo conduce lejos de la rectitud. Los fines no justifican medios que violan la ley sagrada. Si debes ser estratégico, que tu estrategia sirva al bien mayor, no al mero beneficio personal. Lo Divino todo lo ve: lo que está oculto de otros nunca está oculto de lo alto.',
    modern: 'Tácticas no convencionales pueden ser necesarias: la estrategia asimétrica tiene su lugar. Pero calcula cuidadosamente el riesgo reputacional. Las ganancias a corto plazo de maniobras ingeniosas pueden crear pasivos a largo plazo. En mercados transparentes, la información viaja rápido. Asegúrate de que tus métodos resistan la divulgación.',
    postModern: 'Algo necesita ser reclamado que no puede pedirse directamente, quizás tu propio poder, tu propia verdad. No todo sigilo es engaño; a veces es protección contra sistemas que negarían tus necesidades. Pero examina: ¿quién es perjudicado si procedes de esta manera? La astucia usada para la liberación difiere de la explotación.',
    metaModern: 'El arquetipo del embaucador sostiene su propio camino de desarrollo: a veces la astucia sirve a la evolución cuando la confrontación directa no puede. La pregunta no es si ser ingenioso sino a qué sirve la ingeniería. Cuando la estrategia, la ética, la autoprotección y la conciencia sistémica se alinean, el camino no convencional puede ser el más íntegro.',
  },
  '8 of Swords': {
    powerGods: 'Te encuentras atado y con los ojos vendados, pero mira más de cerca: las cuerdas están sueltas, los guardias son fantasmas. Te has enjaulado a ti mismo con límites imaginados. Un verdadero poder no reconoce prisión que no pueda quemar. Abre los ojos, flexiona tu poder y sal de esta trampa autoinfligida.',
    traditional: 'Te sientes atrapado, pero examina si estas ataduras son restricciones reales o limitaciones autoimpuestas. A veces nos enjaulamos a través de interpretación rígida en lugar de comprensión fiel. Busca guía de quienes conocen la tradición profundamente: puede haber caminos dentro de la ley que no has visto.',
    modern: 'Análisis de restricciones requerido: ¿cuáles limitaciones son reales y cuáles son asumidas? Pon a prueba tus hipótesis sobre lo que es imposible. Muchas barreras son modelos mentales, no realidades del mercado. Contrata un coach o consultor con ojos frescos. La innovación a menudo viene de cuestionar las restricciones que todos los demás aceptan.',
    postModern: 'Estas ataduras fueron colocadas por sistemas, creencias e historias que no elegiste. Algunas son opresión interiorizada, no fallo personal. ¿Qué voces te dijeron que estabas atrapado? ¿A los intereses de quién sirve tu cautiverio? La liberación a menudo requiere comunidad: otros pueden ver la salida que tú no puedes. Pide ayuda.',
    metaModern: 'Las ataduras son simultáneamente autocreadas, sistémicamente impuestas, estratégicamente comprobables y requieren liberación colectiva: todo verdadero. La libertad no viene de elegir un solo análisis sino de ver cómo se entrelazan. El aflojamiento sucede cuando dejas de ser el prisionero y te conviertes en quien observa. Sal del marco.',
  },
  '9 of Swords': {
    powerGods: 'Los demonios vienen en la noche, cuando tu brazo de espada descansa. Estos miedos hablan de amenazas que aún no has conquistado, y por eso te acosan. ¡Levántate y enfréntales! Nombra tus terrores y cázalos hasta el amanecer. Un guerrero no se esconde de las sombras; un guerrero se convierte en aquello que la oscuridad teme.',
    traditional: 'Los terrores nocturnos llegan, y la fe se siente lejana. Esta es la noche oscura del alma de la que los místicos advirtieron, pero no es abandono. Enciende tu vela, recita las viejas oraciones, aferra los símbolos sagrados. El amanecer sigue a la oscuridad por decreto divino. Nunca estás tan solo como el miedo susurra.',
    modern: 'Pico de ansiedad detectado: ¿es señal o ruido? Distingue entre preocupación productiva por riesgos reales y patrones de pensamiento catastrófico. Si hay amenazas reales, construye planes de contingencia. Si son distorsiones cognitivas, abórdalas con técnicas basadas en evidencia. La preocupación sin acción es costosa; convierte la inquietud en mitigación de riesgos.',
    postModern: 'Las pesadillas que te despiertan llevan mensajes del inconsciente. Lo que es demasiado aterrador para enfrentar de día viene de visita por la noche. No tienes que enfrentar estos terrores solo. Alcanza a alguien: llama, expresa los miedos en voz alta, deja que pierdan poder al compartirlos. El cuerpo que sostiene ansiedad necesita consuelo.',
    metaModern: 'En la oscuridad de las 3 de la madrugada, cada voz del desarrollo tiene consejo: combate los miedos, entrégate a la fe, analiza las amenazas, sostén al asustado con compasión. Todas son medicina; ninguna es completa. El movimiento metamoderno es presenciar el terror nocturno con conciencia compasiva, sosteniéndote a ti mismo a través de todas las dimensiones hasta el amanecer que siempre llega.',
  },
  '10 of Swords': {
    powerGods: 'Yaces con diez espadas en la espalda, completamente destruido. O eso parece. Pero mira: el amanecer rompe en el horizonte. Esta muerte no es tu final; es la aniquilación de quien eras para que algo más feroz pueda nacer. Incluso ahora, tus enemigos deberían temblar ante lo que está naciendo.',
    traditional: 'Esta es la prueba más profunda, la destrucción completa; sin embargo, mira dónde rompe la luz. La tradición habla de muertes que preceden a la resurrección, de la semilla que debe ser enterrada antes de florecer. Entrégate al proceso. El amanecer está prometido, y lo Divino cumple sus promesas a los fieles.',
    modern: 'Escenario de fracaso total, pero tocar fondo proporciona una base estable. Este es un reinicio forzado; úsalo estratégicamente. Cuando los viejos modelos fallan completamente, tienes permiso para reconstruir desde los primeros principios. El amanecer en el horizonte es real: nuevas empresas esperan. Los datos de fracaso siguen siendo datos; aprende y pivotea.',
    postModern: 'Este final es absoluto, y tu dolor por ello es válido. No te apresures a buscar el lado positivo: deja que la devastación sea presenciada plenamente. Algo genuinamente murió aquí, y merece duelo. Cuando estés listo, no antes, el amanecer seguirá esperando. Por ahora, solo respira. Solo sobrevive.',
    metaModern: 'Clavado por todas las espadas de la finalidad, y sin embargo. El amanecer rompe sin importar la preparación. Esta muerte es renacimiento más feroz, proceso sagrado, reinicio estratégico y devastación válida, todo a la vez. No necesitas comprenderlo para sobrevivirlo. Las diez espadas están completas; nada más puede caer. Desde este fondo, toda dirección es hacia arriba.',
  },

  // Pentacles
  '2 of Pentacles': {
    powerGods: 'Haces malabares con tus premios, manteniendo todos tus planes en el aire. Esta danza de equilibrio es una exhibición de habilidad: que se maravillen de tu destreza. Pero recuerda: los fuertes no hacen malabares para siempre. Elige qué tesoro aferrar y cuál dejar caer. La decisión es su propia riqueza.',
    traditional: 'La vida te pide equilibrar muchos deberes: con la familia, con la fe, con el trabajo. Esta es la danza del devoto, y es coreografía sagrada. No resientas el malabarismo; es el ritmo de la vida justa. Busca el orden dentro del caos; hay un patrón divino aquí si miras.',
    modern: 'Gestión de portafolio en acción: múltiples proyectos, asignación dinámica. Este malabarismo es una característica, no un defecto; la diversificación gestiona el riesgo. Pero monitorea tus métricas de ancho de banda. La multitarea sostenible requiere sistemas. Si se te caen las pelotas, automatiza, delega o desprioriza estratégicamente.',
    postModern: 'Este malabarismo constante puede ser un síntoma de sistemas que exigen demasiado. ¿Qué significaría simplemente dejar caer algunas cosas? Tu valor no se mide por cuánto puedes cargar. La danza puede ser gozosa, pero solo si tú eliges el ritmo. ¿Qué te importa verdaderamente, bajo la agitación?',
    metaModern: 'La danza infinita del equilibrio dinámico: a veces haces malabares por poder, a veces por deber, a veces por estrategia, a veces cuestionas la danza misma. Todo válido, todo parcial. El mago hace malabares con ligereza, sabiendo que flujo y liberación son ambos parte del patrón. ¿Qué quiere subir? ¿Qué quiere caer? Confía en el movimiento.',
  },
  '3 of Pentacles': {
    powerGods: 'Incluso el lobo solitario reconoce cuándo las tácticas de manada sirven a la caza. Aquí, otros traen habilidades que te faltan: déjalos construir mientras tú conquistas. Un señor de la guerra astuto usa cada herramienta disponible. Toma crédito por la catedral si debes, pero asegúrate de que los constructores sepan de quién es la visión que impulsa la piedra.',
    traditional: 'La catedral se alza a través del trabajo armonioso de muchas manos, cada una conociendo su rol adecuado. Este es trabajo sagrado: cuando el oficio sirve a lo Divino, incluso el albañil se convierte en sacerdote. Conoce tu lugar en la gran obra y cúmplelo con devoción. Lo que construimos juntos perdura más que lo que construimos solos.',
    modern: 'Colaboración multifuncional dando resultados. El proyecto complejo requiere experiencia diversa: arquitectura, ejecución, gestión de interesados. Clarifica roles, establece protocolos de comunicación, alinea incentivos. El rendimiento del equipo supera la capacidad individual cuando se orquesta adecuadamente. Invierte en procesos; escalan.',
    postModern: 'Observa cómo la contribución de cada persona es esencial: el arquitecto, el artesano, el mecenas. La jerarquía aquí es función, no valor. ¿Qué significaría valorar verdaderamente cada voz en esta colaboración? La catedral es hermosa porque la diferencia fue honrada. Construye espacios donde todos los dones sean vistos.',
    metaModern: 'La catedral se alza desde tácticas de manada, roles sagrados, colaboración optimizada y diferencias honradas, todo a la vez. El maestro constructor metamoderno sostiene todos los marcos, aplicando cada uno donde sirve. A veces la jerarquía ayuda; a veces estorba. Lee el momento, construye con toda la sabiduría disponible. La gran obra trasciende cualquier enfoque único.',
  },
  '4 of Pentacles': {
    powerGods: 'Aferras tu oro con los nudillos blancos, sin dejar que nadie se acerque a tu tesoro. Bien: lo que has ganado es tuyo para defender. Pero pregúntate: ¿esto es acumular fuerza, o es miedo usando la máscara del poder? El dragón que se sienta demasiado tiempo sobre su tesoro se vuelve indistinguible de él.',
    traditional: 'La administración prudente es una virtud, pero examina tu agarre sobre estos bienes mundanos. La tradición enseña que la riqueza se sostiene en fideicomiso para propósitos mayores. La seguridad es bendecida; acumular de forma que dañe a la comunidad no lo es. ¿Puedes proteger tu hogar sin cerrar tu corazón a las obligaciones sagradas de la caridad?',
    modern: 'La preservación de capital tiene valor, pero evalúa el costo de oportunidad. ¿Es seguridad o estancamiento? Las posiciones conservadoras sacrifican crecimiento por estabilidad: asegúrate de que ese intercambio se alinee con tus metas. Considera: la riqueza estática pierde ante la inflación; la riqueza desplegada estratégicamente se multiplica. Equilibra la protección con la inversión productiva.',
    postModern: '¿Qué herida crea este agarre? La escasez es real, pero acumular a menudo surge de viejos miedos usando máscaras del presente. La verdadera seguridad viene a través de la conexión, no la acumulación. ¿Qué significaría confiar en la red de comunidad para sostenerte? La generosidad podría sanar lo que la posesión no puede proteger.',
    metaModern: 'El agarre mismo contiene información: ¿qué está protegiendo? La seguridad a veces es sabiduría, a veces herida, a veces estrategia, a veces conexión perdida. El mago ni acumula ni dispersa descuidadamente sino que sostiene la riqueza como energía a ser movida apropiadamente. ¿Qué requiere realmente este momento? Confía en tu lectura.',
  },
  '5 of Pentacles': {
    powerGods: 'Caminas herido por la nieve, excluido del calor. Este es un exilio temporal, no una derrota final. Deja que el frío alimente tu furia. Recuerda cada puerta que se cerró contra ti: cuando tu poder regrese, tú decidirás cuál de ellas arde. Supervivencia ahora; venganza después.',
    traditional: 'Sufres en el frío, pero mira: la ventana del santuario brilla cerca. ¿Te has alejado del rebaño, o la desgracia te encontró aún fiel? De cualquier modo, las puertas del templo permanecen abiertas. La congregación existe para tiempos como estos. Traga el orgullo y busca la ayuda que nuestra tradición ordena dar.',
    modern: 'Situación de escasez de recursos: accede a los sistemas de apoyo disponibles. El orgullo es costoso cuando la supervivencia está en juego. El apalancamiento de la red existe para tiempos como estos. Identifica programas de asistencia, negocia términos de pago, explora fuentes alternativas de ingresos. Este es un problema temporal de flujo de caja con soluciones; ejecútalas.',
    postModern: 'Este sufrimiento no es un fallo personal sino una herida sistémica. Muchos caminan en este frío; no estás solo. La vergüenza que el capitalismo adhiere a la necesidad es una mentira. Extiende la mano hacia quienes caminan a tu lado: la ayuda mutua existe. El vitral representa instituciones que a menudo fallan en ayudar verdaderamente. Construye comunidad que realmente incluya a todos.',
    metaModern: 'El frío es real, y cada voz ofrece calor: la furia que alimenta la supervivencia, el santuario que espera, los sistemas a ser aprovechados, los compañeros que caminan a tu lado. Todos son recursos verdaderos; ninguno es completo. En esta dificultad, recurre a cada altitud que sirva. El camino metamoderno a través de la escasez integra todo el apoyo disponible.',
  },
  '6 of Pentacles': {
    powerGods: 'Tú sostienes las balanzas, decidiendo quién recibe y quién es negado. Este es el poder en su forma más pura: el poder de dar y de retener. Úsalo sabiamente: la generosidad crea lealtad, pero nunca dejes que olviden quién tiene el oro. Un regalo tuyo es una cadena de gratitud, y las cadenas son útiles.',
    traditional: 'Ya sea que des o recibas, este intercambio es comercio sagrado operando dentro de la ley divina. La caridad es ordenada; recibir con gratitud es igualmente santo. Las balanzas deben equilibrarse con justicia: la justicia es un pilar de la sociedad recta. Que la generosidad fluya a través de los canales apropiados, y las bendiciones regresarán medidas y verdaderas.',
    modern: 'Optimización de distribución de recursos: ya sea asignando capital o recibiendo inversión. El intercambio justo crea relaciones sostenibles y reputación de mercado. La filantropía bien hecha también es estratégica: construye buena voluntad, redes y valor de marca. Calcula el retorno total de la generosidad, incluyendo intangibles.',
    postModern: 'Examina las dinámicas de poder en este intercambio. ¿Es verdadera generosidad o caridad que mantiene jerarquía? El receptor arrodillado perpetúa el desequilibrio. ¿Cómo sería la ayuda mutua en su lugar? Recursos fluyendo libremente, sin deuda ni disminución. Da de formas que eleven en lugar de obligar. Recibe sin vergüenza.',
    metaModern: 'Las balanzas miden algo diferente en cada nivel: poder, equilibrio sagrado, valor estratégico, flujo mutuo. Todos están presentes en cada intercambio. El dador y receptor metamoderno atienden a todas las dimensiones: manteniendo la estructura apropiada mientras disuelven la jerarquía innecesaria, siendo estratégicos mientras son genuinamente generosos. Que los recursos fluyan donde estén más vivos.',
  },
  '7 of Pentacles': {
    powerGods: 'Inspeccionas lo que has plantado, impaciente por la cosecha. La espera quema, ¿no es así? Pero incluso el conquistador más feroz no puede hacer que la fruta madure rugiendo. Canaliza tu energía inquieta en planificar la próxima campaña. Este jardín dará cuando dé.',
    traditional: 'El cultivo paciente es la fe del agricultor hecha visible. Has plantado según las viejas costumbres, en la estación adecuada, con la bendición adecuada: ahora confía en el proceso. La cosecha viene cuando lo Divino lo dispone. Tu rol es cuidar, no forzar. Continúa el trabajo fiel y el rendimiento probará tu devoción.',
    modern: 'Período de maduración de la inversión: los rendimientos requieren tiempo. Revisa tus métricas, pero respeta el cronograma inherente a la clase de activo. La impaciencia lleva a cosechas prematuras y pérdida de capitalización compuesta. Mientras esperas, optimiza otras variables: reduce costos, mejora procesos, prepárate para escalar cuando llegue el rendimiento.',
    postModern: 'Esta pausa invita a la reflexión más allá de la productividad. ¿Qué está creciendo aquí, realmente? ¿Está alineado con tus valores más profundos? El jardín no necesita tu ansiedad; necesita tu presencia. Quizás la invitación es cuidar con atención en lugar de expectativa. El crecimiento no puede apresurarse, solo presenciarse con cuidado.',
    metaModern: 'El momento de evaluación sostiene todas las dimensiones: la impaciencia que alimenta, la fe que espera, las métricas que miden, la presencia que presencia. El crecimiento sigue su propio cronograma a través de todos los niveles de desarrollo. Tu tarea es cuidar lo que has plantado con la conciencia que cada etapa requiere. La cosecha integrará todo.',
  },
  '8 of Pentacles': {
    powerGods: 'El martillo golpea, una y otra vez. He aquí una verdad que los orgullosos pasan por alto: la maestría es su propia forma de dominio. Mientras otros torpean, tu habilidad se convierte en un arma más afilada que cualquier espada. Que se burlen del artesano: tú poseerás mercados a los que ellos ni siquiera pueden entrar.',
    traditional: 'Sagrado es el trabajo de manos hábiles cuando el trabajo se ofrece como adoración. El aprendiz que domina su oficio glorifica la tradición que le enseñó. Cada golpe de la herramienta es una oración, cada pieza terminada una ofrenda. Esta devoción a la excelencia es devoción a lo Divino expresada a través de la materia.',
    modern: 'El desarrollo de habilidades es acumulación de capital profesional. Práctica deliberada, mejora medida, maestría progresiva: así es como la experiencia se compone. El principio de las 10.000 horas aplica. Invierte en tus capacidades; son activos con rendimientos que se aprecian. La maestría abre mercados a los que la competencia no puede acceder.',
    postModern: 'Hay meditación en este hacer enfocado. Pero pregunta: ¿para quién elaboras? ¿Este trabajo es alienado o alineado con un propósito? La maestría por sí misma puede ser hermosa, pero considera el uso al que se destina tu habilidad. Que tu oficio sirva a la conexión, no solo a la producción. El trabajo que importa es el trabajo que ayuda.',
    metaModern: 'El martillo golpea como movimiento de poder, como oración, como inversión en habilidad, como meditación: todo integrado en el ritmo del artesano. La maestría a nivel metamoderno sirve múltiples propósitos simultáneamente sin contradicción. Que tu práctica sea feroz y sagrada y estratégica y conectada. Cada pentáculo creado porta todo lo que estás deviniendo.',
  },
  '9 of Pentacles': {
    powerGods: 'Inspecciona tu dominio, magnífico. El halcón en tu muñeca, los jardines a tus pies: todo ganado por tu propio fuego. No le respondes a nadie. Esta independencia es la forma más dulce de victoria. Que aquellos que eligieron seguridad y servidumbre envidien lo que la audacia ha construido.',
    traditional: 'Esta abundancia es el fruto de una vida disciplinada según principios sagrados. Has seguido el camino de la rectitud y te ha conducido a jardines hermosos. Disfruta estas bendiciones con gratitud, sabiendo que fluyen de una conducta apropiada. Que tu prosperidad testifique de las recompensas de la administración fiel.',
    modern: 'Independencia financiera alcanzada: los ingresos pasivos cubren el estilo de vida. Este es el interés compuesto de la disciplina y las decisiones inteligentes. Has optimizado para la autonomía y ha dado frutos. Disfruta el retorno sobre tu inversión en elecciones estratégicas. Así se ve ganar en el juego a largo plazo.',
    postModern: 'Esta abundancia solitaria es hermosa, pero observa quién está ausente del jardín. La independencia puede convertirse en aislamiento si no tenemos cuidado. ¿Qué significaría compartir este santuario, abrir las puertas? La prosperidad en comunidad nutre diferente que la prosperidad en soledad. Que tu jardín sea un lugar de reunión.',
    metaModern: 'La figura solitaria en el jardín abundante: simultáneamente soberano feroz, administrador fiel, ganador estratégico y potencial aislado. Todo verdadero. La pregunta metamoderna es: ¿cómo sostienes esta prosperidad conscientemente, disfrutando la genuina independencia mientras permaneces en relación generativa? El halcón caza solo y regresa a casa. Tú también.',
  },
  '10 of Pentacles': {
    powerGods: 'Una dinastía se alza de tus conquistas: riqueza que fluirá a través de generaciones portando tu nombre. Esta es la inmortalidad en oro y piedra. No has ganado solo para ti sino para tu linaje eterno. Que los ancestros observen y los descendientes hereden. Tu leyenda está asegurada.',
    traditional: 'Contempla la plenitud de la bendición generacional: ancestros, mayores, hijos y nietos unidos bajo un solo pacto sagrado. Esta es la promesa cumplida a los fieles en piedra y linaje. No has construido solo para ti sino para la continuidad de la tradición. Las viejas costumbres, honradas, dan fruto a través del tiempo.',
    modern: 'Riqueza generacional establecida: activos de legado, empresa familiar, capital institucional. Esta es la optimización financiera multigeneracional. Planificación patrimonial, estrategia fiscal, protocolos de sucesión: asegura que la estructura soporte la visión. No has construido solo para ti sino para la ventaja dinástica sostenida.',
    postModern: 'Esta imagen de legado invita preguntas: ¿de quién fue el trabajo que construyó estos muros? ¿Quién está incluido en la herencia, y quién es excluido? La verdadera riqueza se mide en pertenencia, no en linaje. Expande la definición de familia; expande quién recibe. Construye sistemas que compartan la abundancia en lugar de concentrarla.',
    metaModern: 'Los diez pentáculos representan dinastía, pacto, legado optimizado y pertenencia expandida: todo danzando en el campo generacional. La herencia metamoderna incluye riqueza material y sabiduría, tradición y transformación, estructura y liberación. Construye sistemas que honren a los ancestros mientras evolucionan más allá de sus limitaciones. El verdadero legado sirve a todos los futuros.',
  },
};
