export const numerologyMeanings = {
  1: 'The number of origins and singular will. One is the undivided whole before differentiation—pure consciousness, the first cause, the creative force that needs no other to exist. It speaks to self-origination, leadership, and the power that arises from complete self-sufficiency.',
  2: 'The number of duality, partnership, and choice. Two represents balance, cooperation, and the interaction between opposing forces. It speaks to decisions, relationships, and the need to find harmony between different aspects.',
  3: 'The number of creation and growth. Three represents the synthesis of opposing forces creating something new. It speaks to creativity, self-expression, collaboration, and the manifestation of ideas into form.',
  4: 'The number of stability and foundation. Four represents order, structure, and solid foundations. It speaks to manifestation in the material world, establishing boundaries, and creating lasting security.',
  5: 'The number of change and disruption. Five represents instability, conflict, and necessary changes. It speaks to freedom, adventure, and the challenges that lead to growth and learning.',
  6: 'The number of harmony and balance. Six represents equilibrium, love, and beauty. It speaks to nurturing, healing, responsibility, and finding solutions that benefit all.',
  7: 'The number of wisdom and spirituality. Seven represents inner knowing, analysis, and spiritual awareness. It speaks to seeking deeper truth, introspection, and understanding beyond the material.',
  8: 'The number of power and manifestation. Eight represents material success, authority, and personal power. It speaks to achievement, strength, and the ability to make things happen in the physical world.',
  9: 'The number of completion and fulfillment. Nine represents achievement, culmination, and wisdom gained through experience. It speaks to reaching goals, spiritual awareness, and preparing for new cycles.',
};

export const signsModality = {
  'Aries': 'Cardinal',
  'Taurus': 'Fixed',
  'Gemini': 'Mutable',
  'Cancer': 'Cardinal',
  'Leo': 'Fixed',
  'Virgo': 'Mutable',
  'Libra': 'Cardinal',
  'Scorpio': 'Fixed',
  'Sagittarius': 'Mutable',
  'Capricorn': 'Cardinal',
  'Aquarius': 'Fixed',
  'Pisces': 'Mutable',
};

export const modalityDescriptions = {
  'Cardinal': 'Cardinal signs initiate each new season—Aries (Spring), Cancer (Summer), Libra (Autumn), Capricorn (Winter). They embody the principle of beginning: energetic, ambitious, and oriented toward launching new cycles. Cardinal energy is the spark that starts fires, the idea that becomes action, the impulse that sets everything in motion.',
  'Fixed': 'Fixed signs occupy the height of each season—Taurus, Leo, Scorpio, Aquarius. They embody the principle of concentration: persistent, determined, and oriented toward sustaining what has been established. Fixed energy is the will that keeps the fire burning, the loyalty that deepens roots, the intensity that refuses to abandon what has begun.',
  'Mutable': 'Mutable signs close each season—Gemini, Virgo, Sagittarius, Pisces. They embody the principle of transition: adaptable, versatile, and oriented toward preparing the ground for what comes next. Mutable energy is the wisdom that knows when to release, the flexibility that finds the thread of continuity across change, the grace that makes endings into beginnings.',
};

export const signsRulingPlanet = {
  'Aries': 'Mars',
  'Taurus': 'Venus',
  'Gemini': 'Mercury',
  'Cancer': 'Moon',
  'Leo': 'Sun',
  'Virgo': 'Mercury',
  'Libra': 'Venus',
  'Scorpio': 'Mars',
  'Sagittarius': 'Jupiter',
  'Capricorn': 'Saturn',
  'Aquarius': 'Saturn',
  'Pisces': 'Jupiter',
};

export const signsDates = {
  'Aries': 'March 21 – April 19',
  'Taurus': 'April 20 – May 20',
  'Gemini': 'May 21 – June 20',
  'Cancer': 'June 21 – July 22',
  'Leo': 'July 23 – August 22',
  'Virgo': 'August 23 – September 22',
  'Libra': 'September 23 – October 22',
  'Scorpio': 'October 23 – November 21',
  'Sagittarius': 'November 22 – December 21',
  'Capricorn': 'December 22 – January 19',
  'Aquarius': 'January 20 – February 18',
  'Pisces': 'February 19 – March 20',
};

export const signsCardData = {
  'Aries': {
    majorArcana: 'The Emperor',
    cardKey: 'emperor',
    romanNumeral: 'IV',
    arcanaNumber: 4,
    title: 'Lord of Flame and Lightning; King of the Spirit of Fire',
    description: 'The Emperor represents the principle of order arising from chaos—the Martian fire of Aries shaped into governance, structure, and sovereign authority. He is the archetypal Father, the first principle of form-giving, the yang force that defines and defends. In Golden Dawn symbolism, he sits upon the Ram-headed throne, wielding the ankh and the orb, the life force organized into dominion.',
    jungian: 'The Emperor embodies the father archetype in its fullest expression—the organizer of the psyche\'s raw energies into coherent identity. He represents the logos principle that structures the chaos of unconscious contents into directed will. In individuation, he appears when the ego must take authority over itself, establishing the inner king who rules without tyranny.',
    powerGods: 'You are the Emperor because you have claimed what lesser wills abandoned. The Rams charge—but only you hold the throne. Let no one question your authority without earning that right through fire. The orb in your hand is the world; the staff is your decree. Every boundary you draw is law. Rule with certainty, for hesitation invites usurpers.',
    traditional: 'The Emperor embodies sacred hierarchy—the divine right to order that flows from above and expresses below. He is the earthly representative of divine law, ruling by the mandate of heaven as interpreted through the traditions his predecessors established. Proper governance is holy governance: just, firm, and rooted in the eternal forms that precede him.',
    modern: 'The Emperor is the CEO, the systems architect, the master strategist who transforms vision into organizational reality. He governs through clear roles, defined processes, and measurable accountability. His power comes not from force alone but from designing structures that scale, that outlast his tenure, that create order beyond his presence.',
    postModern: 'Examine the Emperor\'s throne carefully—who built it, and at whose expense? Power must be interrogated. The good ruler asks: whose voices are absent from this council? Authority becomes tyranny when it stops questioning itself. True leadership decentralizes power while maintaining accountability. Hold authority lightly; governance is a service, not a possession.',
    metaModern: 'The Emperor holds structure and chaos both—he knows his dominion is both necessary and provisional. He rules with conviction while remaining open to evolution. The laws he makes, he can unmake when they no longer serve life. He is both the system and the one who transcends the system to maintain it. Iron and water, form and flow.',
  },
  'Taurus': {
    majorArcana: 'The Hierophant',
    cardKey: 'hierophant',
    romanNumeral: 'V',
    arcanaNumber: 5,
    title: 'Lord of the Mysteries of the Pentagram; Magus of the Eternal Gods',
    description: 'The Hierophant represents the principle of sacred tradition—the bridge between divine revelation and human understanding. Venus-ruled Taurus grounds the celestial into the earthly through ceremony, teaching, and the transmission of wisdom through lineage. He is the keeper of the mysteries, the initiator who stands between worlds and passes the flame of knowledge from hand to hand across generations.',
    jungian: 'The Hierophant represents the archetype of the Wise Elder or Senex—the carrier of collective wisdom, the personification of the superego at its most constructive. He appears in the psyche when the individual needs to connect with something larger than personal history: tradition, lineage, accumulated wisdom. In shadow, he becomes rigid dogma; in health, he offers the container that allows true growth.',
    powerGods: 'Wisdom is power more enduring than muscle. You hold the keys that others cannot copy—the secret formulae, the initiatory knowledge, the codes that open doors sealed to the uninitiated. Others bow before you not from fear but from recognition of what you carry. Transmit your power selectively; knowledge given to the unready is power squandered.',
    traditional: 'The Hierophant is the living repository of sacred law—the priest-king who interprets the eternal for the temporal age. Through him, the ancient teachings flow unbroken from the primordial revelation. Honor this role with humility; you are the vessel, not the source. The teachings trust you with their continuity. Guard them, teach them, live them faithfully.',
    modern: 'The Hierophant is the master teacher, the institution-builder, the creator of curricula that transmit expertise across generations. He understands that knowledge must be systematized to scale. The mentor who creates mentors, the teacher who teaches teachers—this is how wisdom compounds across time. Build systems that outlast your personal tenure.',
    postModern: 'The Hierophant\'s robes hide many things, including who was excluded from the tradition he carries. Question what is taught as universal truth—every tradition is also a perspective. The wisdom is real, but so is its partiality. Who gets to receive these teachings? What have the gatekeepers kept from the gates? Sacred knowledge should liberate, not bind.',
    metaModern: 'The Hierophant bridges the ancient and the evolving—he carries tradition not as cage but as gift. He knows that sacred forms must periodically die to be reborn. He transmits the essence, not merely the letter. The true initiation is learning to hold wisdom and its questioning in the same hands, to be simultaneously devoted to and critical of the tradition that formed you.',
  },
  'Gemini': {
    majorArcana: 'The Lovers',
    cardKey: 'lovers',
    romanNumeral: 'VI',
    arcanaNumber: 6,
    title: 'Lord of the Oracles of the Mighty Gods; Children of the Voice Divine',
    description: 'The Lovers represents sacred choice, the union of opposites, and the oracular moment when the soul must choose its path. Mercury-ruled Gemini embodies the tension between duality—conscious and unconscious, angel and shadow, known and unknown. The blessing from above descends upon the archetypal couple, asking: will you integrate what you have kept separate?',
    jungian: 'The Lovers represents the coniunctio—the sacred marriage of opposites in the psyche. It symbolizes the encounter with the anima/animus, the soul-complement that exists as our undiscovered half. This card appears when the individuation process requires integration of repressed aspects of self. The choice depicted is always between familiar limitation and the riskier wholeness of genuine union with one\'s shadow.',
    powerGods: 'The fork in the road is yours alone. Choose with your fire, not with their fear. The angel above blesses both paths—but only the path you seize with full conviction becomes yours. Refuse the choice and you stand at the crossroads forever, prey to any wind. The strong choose. Then they make their choice the right one.',
    traditional: 'The sacred union depicted here is blessed from above—this is covenant, consecrated by divine witness. The choice before you is not merely practical but eternal: what vows will you speak, what bonds will you honor? The traditions of marriage and alliance exist because some commitments are too weighty for personal judgment alone. Seek blessing before you bind.',
    modern: 'The Lovers represents strategic alignment—the power of combining complementary capabilities to create outcomes neither could achieve alone. Whether partnership, merger, or alliance, the key is clear values-alignment and complementary strengths. Before committing, define terms explicitly. The best partnerships are built on honesty about what each brings and what each needs.',
    postModern: 'All the beautiful complexity of the Lovers—the choice it presents holds more than it shows. The angel above blesses, but who wrote the angel\'s script? Examine who benefits from this union, what is surrendered, what is gained. Authentic love expands freedom; authentic partnership honors both parties\' wholeness. The blessing should come from within as well as from above.',
    metaModern: 'The Lovers holds every dimension of union—sacred vow and strategic alliance, shadow integration and tender connection, oracular choice and intimate commitment. The deepest love is conscious—knowing what you choose and why, carrying the full weight of that choice with clear eyes and an open heart. Choose completely. Let the choice choose you back.',
  },
  'Cancer': {
    majorArcana: 'The Chariot',
    cardKey: 'chariot',
    romanNumeral: 'VII',
    arcanaNumber: 7,
    title: 'Child of the Powers of the Waters; Lord of the Triumph of Light',
    description: 'The Chariot represents the triumph of will over opposing forces—the Moon-ruled Cancer energy channeled into purposeful motion. The Charioteer controls the black and white sphinxes not through force but through concentrated intent, steering between contradictions through the power of unified will. He carries the Holy Grail, the symbol of the emotional depths he has mastered without denying.',
    jungian: 'The Chariot represents the ego triumphant in its solar phase—the conscious will that has learned to harness the opposing drives of the unconscious without crushing them. The Charioteer\'s armor is crystallized will; he has forged his inner contradictions into forward motion. This card appears when the psyche has reached a degree of integration sufficient to move purposefully through conflict.',
    powerGods: 'You have tamed what others fled from—harnessed the opposing forces that would have torn lesser warriors apart. Now the city trembles as you pass through its gates. This is the victory of iron will: not that you destroyed the beasts, but that you made them serve you. The crown of stars is earned by those who turn contradiction into momentum.',
    traditional: 'The Charioteer enters in triumph, crowned with stars, bearing the sacred vessel. This victory honors all the traditions of righteous conquest—the warrior who fights not for glory alone but for the sacred purpose that sent him forth. He returns not to boast but to fulfill the covenant of service that girded him for battle. Receive the triumph humbly, for it belongs to what sent you.',
    modern: 'The Chariot represents mastery of execution—the project manager, the athlete, the leader who moves teams through impossible conditions through sheer coherence of intention. Direction clarity cuts through ambiguity; momentum compounds with each aligned step. The charioteer doesn\'t control everything—only the direction of unified will.',
    postModern: 'The Chariot\'s triumph—but at what cost to the lands through which it has driven? Examine the victory: what voices were silenced, what paths were paved over? True leadership negotiates with the sphinxes; it doesn\'t merely subdue them. The stars in his crown represent possibility, not superiority. How do we win without dominating?',
    metaModern: 'The Chariot integrates the triumphant will, the sacred victor, the execution master, and the one who questions the road—all steering together. The deepest triumph is not over others but over the parts of yourself that would stop you. The charioteer moves at the speed of integration, which is sometimes very fast and sometimes requires stillness.',
  },
  'Leo': {
    majorArcana: 'Strength',
    cardKey: 'strength',
    romanNumeral: 'VIII',
    arcanaNumber: 8,
    title: 'Daughter of the Flaming Sword; Leader of the Lion',
    description: 'Strength represents the mastery of primal force through love rather than violence—the Sun-ruled Leo energy expressed as radiant courage that transforms rather than subdues. The figure adorned with flowers opens the lion\'s mouth not through dominance but through the power of gentle certainty, demonstrating that the heart\'s strength exceeds the muscles\' power. The infinite lemniscate above her head shows this is not personal power but cosmic force flowing through her.',
    jungian: 'Strength represents the integration of the beast—the Shadow in its most primal form approached not with suppression or projection but with loving awareness. This is the anima in its solar aspect, the feminine principle that tames the masculine instinctual drives not by opposing them but by transforming them through relationship. The card appears when shadow integration is possible through compassion rather than confrontation.',
    powerGods: 'Here is the truth no brute understands: the lion yields to the one who is not afraid. Your fire is so total that even the king of beasts feels it and bows. This is the highest dominance—not the conquest of the sword, but the radiance that makes conquest unnecessary. Your courage is a field that tames the wild places in everything around you.',
    traditional: 'She opens the lion\'s mouth with serene faith—this is the grace that flows through the truly devoted. Her strength is not her own; it is borrowed from the sacred. The traditions of inner mastery all point here: the holy women who walked unafraid among the beasts, the saints whose purity rendered them untouchable by animal ferocity. Cultivate this interior flame.',
    modern: 'Strength represents the psychological safety that enables high performance—the leader whose calm under pressure stabilizes the team, whose grounded confidence opens creative possibility. The infinite symbol above her head represents sustainable force, not sprint energy. Build cultures where courage is quiet, where conviction doesn\'t require volume, where excellence flows naturally from security.',
    postModern: 'The lion and the maiden—but who wrote the roles? Strength is not only feminine gentleness taming masculine force; it is the integration of all our denied ferocities, the meeting of what we have split off with compassion. What lions have you caged? What roaring parts of yourself await your gentle recognition? True strength includes acknowledging the beast as your own.',
    metaModern: 'Strength holds the solar hero, the holy tamer, the psychologically secure leader, and the shadow-integrator in one gesture of radical openness. The lemniscate indicates that this is not a one-time triumph but an ongoing practice. You open the lion\'s mouth every day. The strength is in continuing to return to that gesture of fearless love, again and again.',
  },
  'Virgo': {
    majorArcana: 'The Hermit',
    cardKey: 'hermit',
    romanNumeral: 'IX',
    arcanaNumber: 9,
    title: 'Prophet of the Eternal; Magus of the Voice of Power',
    description: 'The Hermit represents the inner light held aloft for the path that cannot be walked in company—the Mercury-ruled Virgo quality of refined analysis turned toward the deepest questions of existence. He stands on the mountain peak alone not because he is antisocial but because the altitude of his inquiry has left the crowd behind. His lantern contains a six-pointed star—the light of wisdom, not of certainty.',
    jungian: 'The Hermit represents the archetype of the Wise Old Man—the Self manifesting as a guide from the depths of the unconscious. He appears in dreams and visions when the psyche has reached sufficient development to receive higher-order guidance. He is also the introvert\'s journey inward, the necessary retreat from persona and collective identity to encounter the autonomous inner voice that alone can orient truly.',
    powerGods: 'The mountain is empty except for you—and that is the source of your power. The crowd below has comfort and noise; you have clarity and the lantern that cannot be blown out. The path you have walked has refined you past what average endurance allows. Let them wonder at your isolation. Solitude is not loneliness; it is the laboratory of the sovereign self.',
    traditional: 'The Hermit walks the ancient paths of the desert fathers, the forest sages, the mountain recluses—those who withdrew from the world not in rejection but in love, seeking the silence in which the Divine speaks unmistakably. His lantern is prayer made visible. The light he carries was lit by those before him; he walks to pass it to those who will come.',
    modern: 'The Hermit represents deep work—the focused withdrawal that produces insight unavailable in constant connection. In an attention economy, solitude is the ultimate competitive advantage. The analyst, the researcher, the philosopher who retreats to think clearly produces value that the perpetually distracted cannot access. Schedule the mountain; protect the lantern time.',
    postModern: 'Who has access to the mountain? The Hermit\'s solitude is a privilege—the time and safety to withdraw from the demands of others requires resources not everyone possesses. Genuine wisdom asks: what am I learning in this solitude, and for whom? The light in the lantern is not for keeping. Inner work in service of nothing beyond itself can become spiritual narcissism.',
    metaModern: 'The Hermit holds the wizard\'s solitude, the mystic\'s communion, the analyst\'s depth, and the servant\'s accountability—ascending alone while remaining connected to the human web below. He shines his lantern for those climbing behind him, not to direct their path but to remind them that ascent is possible. His wisdom includes knowing when to descend and return.',
  },
  'Libra': {
    majorArcana: 'Justice',
    cardKey: 'justice',
    romanNumeral: 'XI',
    arcanaNumber: 11,
    title: 'Daughter of the Lords of Truth; Ruler of the Balance',
    description: 'Justice represents cosmic law, the eternal scales upon which all actions are weighed—the Venus-ruled Libra energy expressed as absolute impartiality. The figure is seated between two pillars of the law, holding scales in perfect balance and a double-edged sword that cuts both ways. There is no mercy here that compromises truth, no truth that forgets compassion—only the exact measure of what is.',
    jungian: 'Justice represents the archetype of the Self in its adjudicating function—the psyche\'s capacity to evaluate and integrate with impersonal accuracy. She appears when the individuation process requires honest self-assessment, when the ego must submit to a standard beyond its own preferences. The scales also represent the need to hold opposing truths simultaneously without forcing resolution.',
    powerGods: 'The sword in Justice\'s hand is perfectly balanced and eternally sharp—because power that ignores its own consequences eventually falls on its wielder. The truly powerful understand that the laws they invoke will be applied to them. Govern yourself by the same code you impose on others; then your authority becomes unassailable, because it cannot be accused of hypocrisy.',
    traditional: 'Justice embodies the eternal law that undergirds all righteous order—the principle that the Divine does not play favorites, that every action sets in motion its precise consequence. The traditions of sacred law exist to align human behavior with this cosmic principle. Submit your decisions to honest examination: would they hold in the divine court? What is weighed in the balance of eternity?',
    modern: 'Justice represents systemic accountability—the processes, audits, and balancing mechanisms that keep organizations honest. Good governance requires both the sword (decisive action) and the scales (fair measurement). Build systems where outcomes are tracked, where equity is measured, where the data tells the story that preferences might suppress. Sustainable excellence requires honest evaluation.',
    postModern: 'Justice must be interrogated: who designed these scales? Every legal system reflects the values of those who built it. True justice requires examining who benefits from the current balance, who has been systematically underweighted, what voices have been silenced by the sword. Restorative justice includes repairing harm to those the scales have failed. The balance must include everyone.',
    metaModern: 'Justice holds the sword of fierce truth and the scales of compassionate balance simultaneously. She is impersonal enough to see clearly and personal enough to care about the particular human before her. She knows that perfect justice is asymptotic—always approached, never perfectly achieved. She acts anyway, with the best discrimination available, remaining open to revision.',
  },
  'Scorpio': {
    majorArcana: 'Death',
    cardKey: 'death',
    romanNumeral: 'XIII',
    arcanaNumber: 13,
    title: 'Child of the Great Transformers; Lord of the Gates of Death',
    description: 'Death represents the great transformer—the Mars-ruled Scorpio energy expressed as the irresistible force of ending that clears space for new beginning. The skeletal rider on the pale horse moves through every level of society: pope, king, maiden, child—none are exempt from transformation. The sun rises in the background, not despite the darkness but because of it.',
    jungian: 'Death represents the archetype of transformation—the mercurial figure who guides the ego through necessary dissolution to the renewal of the Self. He appears when the psyche requires the death of an old identity—a persona, a complex, an attachment to a form that has outlived its function. This is never merely destructive; the Jungian death is always in service of deeper life.',
    powerGods: 'Death comes for all, but you have made an ally of it. While lesser souls flee from endings, you dive into the heart of transformation and emerge changed—more dangerous than before. Every death in your life has refined you, stripped away what weakened you, left only what cannot be destroyed. You are not afraid of the pale horse. You ride it.',
    traditional: 'Death\'s card is the thirteenth—the number of transformation in the sacred numerology, the number of the lunar cycle complete. This is the great mystery that all traditions address: what dies is not the soul but the shell. The devoted understand that endings are doorways. Release what must be released; trust the process that has carried countless souls through this threshold before you.',
    modern: 'Death represents the strategic pivot, the sunset of obsolete business models, the necessity of killing what works adequately to make room for what works excellently. The organizations that fail to manage planned endings become unable to begin new things. Build exit protocols, sunset timelines, and healthy processes for letting go. Creative destruction is the engine of renewal.',
    postModern: 'Not all deaths are equal, and not all transformations are chosen. Death has fallen more heavily on some communities than others, by design. Before we speak of transformation, we must grieve what has been unjustly ended. The card\'s impartiality is the aspiration, not the reality. Let the endings be witnessed, the losses mourned, the transformations honored in their full weight.',
    metaModern: 'Death holds the transformer, the threshold guardian, the strategic ender, and the witness to grief—all riding together toward the sunrise. Every level of experience knows death differently, and each knowing is true. The metamodern relationship with death integrates all these—the warrior\'s embrace, the faithful\'s submission, the strategist\'s management, and the griever\'s protest—woven into acceptance of impermanence at the core of being alive.',
  },
  'Sagittarius': {
    majorArcana: 'Temperance',
    cardKey: 'temperance',
    romanNumeral: 'XIV',
    arcanaNumber: 14,
    title: 'Daughter of the Reconcilers; Bringer-Forth of Life',
    description: 'Temperance represents the angelic art of alchemical blending—the Jupiter-ruled Sagittarius energy expressed as the higher synthesis that transcends opposition. The great angel pours the waters of life between two cups in an endless circuit, one foot on land and one in water, mediating between worlds. The solar crown on her forehead and the triangle within the square on her breast represent the integration of spirit in matter.',
    jungian: 'Temperance represents the transcendent function—the psyche\'s capacity to hold tension between opposites until a new symbol or attitude emerges that includes both. This is the alchemical operation of the unconscious: when the conscious mind cannot solve its contradictions, the deeper process combines the elements and precipitates something new. The angel is the Self working through the ego\'s willingness to remain in process.',
    powerGods: 'You have learned what separates the merely powerful from the truly formidable: the art of mixture. Not water alone, nor fire alone—but the precise blend that creates something neither element could become alone. This is the alchemy of strategic genius. Your patience while working with what seems inert is what produces the gold that others cannot make.',
    traditional: 'The angel of temperance embodies the sacred art of measure—the ancient wisdom that knows the proper proportion of all things. Virtue is the mean between extremes; character is built through the discipline of neither too much nor too little. The traditions speak of this angel as the keeper of divine timing, who pours the streams of life in exactly the measure that serves the sacred design.',
    modern: 'Temperance represents the systems thinker who understands feedback loops, who can see that opposing forces can be configured as a circuit rather than a conflict. The innovator who synthesizes rather than chooses wins in complex environments. Build iterative processes where learning flows back into action. The angel\'s endless pouring is the iterative cycle—experiment, refine, experiment again.',
    postModern: 'The angel mediates between worlds—but which worlds, and on whose terms? The synthesis Temperance offers must include the voices of those on the margins of both poles. What gets lost when we blend? What needs to remain distinct? True reconciliation doesn\'t always produce a third thing; sometimes it requires sitting with the discomfort of genuine difference.',
    metaModern: 'Temperance holds the alchemist\'s patience, the sacred measurer\'s virtue, the systems thinker\'s feedback loop, and the reconciler\'s honest witness to difference—all flowing between the cups simultaneously. The angel\'s art is not to impose synthesis but to remain in the process until what wants to emerge, emerges. This is development as flow, growth as endless becoming.',
  },
  'Capricorn': {
    majorArcana: 'The Devil',
    cardKey: 'devil',
    romanNumeral: 'XV',
    arcanaNumber: 15,
    title: 'Lord of the Gates of Matter; Child of the Forces of Time',
    description: 'The Devil represents the Pan-force—the Saturn-ruled Capricorn energy expressing as the binding power of material existence, the shadow that accumulates through attachment to form. The chained figures can remove their bonds; they remain because they have forgotten their own freedom. The Devil holds the torch downward, inverting the spiritual flame into material obsession. Yet the pentagram on his forehead still points upward—matter contains spirit, not spirit\'s enemy.',
    jungian: 'The Devil represents the personal and collective Shadow at its most condensed and seductive. He is the archetype of the Trickster fused with the Shadow—the compensatory force that accumulates everything the ego has denied, repressed, or refused to integrate. He appears in the psyche as compulsion, addiction, and the dark vitality that life denied takes its revenge through. Integration requires neither battle nor submission, but honest acknowledgment.',
    powerGods: 'The chains you see are the chains you chose. Here is the secret the weak use as excuse and the strong use as key: you are bound by exactly as much as you consent to. The Devil shows you the bars you built and dares you to notice your hands could open the lock. The power is not in escaping bondage—it is in choosing which bonds serve your conquest and releasing those that don\'t.',
    traditional: 'The Devil is the great tempter, the adversary who would bind the soul to the transient pleasures of matter and make you forget your eternal nature. The traditions all speak of this test—the desert, the wilderness, the threshold between the age of innocence and the age of choice. He can only hold you through consent. The answer to the adversary is always the same: remember who you are.',
    modern: 'The Devil represents the systemic forces that trap productivity: perverse incentives, sunk cost fallacy, golden handcuffs, organizational cultures that punish truth-telling. See the chains clearly—what structures, incentives, or habituated patterns are consuming your energy? The torch points down because energy that should serve purpose is being consumed by the system itself. Redesign the system.',
    postModern: 'The Devil\'s chains are not only personal—they are systemic, structural, historical. Many chains were not chosen; they were inherited through generations of oppression, poverty, trauma. We must distinguish between the chains we can simply choose to remove and the chains that require collective liberation. Shaming the chained for their chains is not freedom work—it is blame.',
    metaModern: 'The Devil holds the power-seeker\'s key, the devotee\'s temptation, the analyst\'s systemic trap, and the advocate\'s call to collective liberation—all present at the same time. The chains are real and provisional, chosen and systemic, personal and political. True liberation works at every level simultaneously: claiming personal agency while engaging structural change, releasing attachment while acknowledging genuine constraint.',
  },
  'Aquarius': {
    majorArcana: 'The Star',
    cardKey: 'star',
    romanNumeral: 'XVII',
    arcanaNumber: 17,
    title: 'Daughter of the Firmament; Dweller Between the Waters',
    description: 'The Star represents cosmic hope and the nourishing flow of celestial grace—the Saturn/Uranus-ruled Aquarius energy expressed as the eternal pouring of universal waters for collective renewal. The naked figure kneels between the terrestrial and the cosmic, pouring water back into the earth and into the stream simultaneously. The great star above is surrounded by seven lesser stars—the seven planets whose energies she channels for the world\'s healing.',
    jungian: 'The Star represents the anima in her most transpersonal aspect—the healing feminine principle that connects individual consciousness to the cosmic waters of the collective unconscious. She appears after the destruction of the Tower, offering the hope that emerges when ego has been dismantled enough for the larger Self to flow through. This card speaks to the restoration of meaning after crisis, the renewal of trust in the process.',
    powerGods: 'You have survived what destroyed others, and now you pour your hard-won wisdom into the collective stream. This is the rarest power: the one who can nourish others without diminishing themselves, because their source is not personal but cosmic. Let your gifts flow freely; the star above ensures replenishment. Your abundance serves your authority.',
    traditional: 'The Star is the celestial gift after the night\'s ordeal—the promise of the sacred that holds even when the earthly structures fail. She pours the divine waters back into the world, honoring both the material and the spiritual in a single gesture. This is the consecration of hope: the faith that the cosmos is fundamentally benevolent, that the waters of grace are inexhaustible.',
    modern: 'The Star represents the visionary who rebuilds after failure with a clearer map—the social entrepreneur, the innovator who has survived enough setbacks to understand which waters to pour where. She is both grounded (one foot on earth) and connected to broader flows (one foot in water). Her optimization is for system health, not personal accumulation. Regenerative design.',
    postModern: 'Who has access to the starlight? The naked figure\'s vulnerability is beautiful—and also a reminder that such openness is only safe in certain conditions. The waters she pours so freely—whose rivers does she draw from? Universal hope must be interrogated: whose hope, and at what cost? The Star\'s gift is real, but it requires the ground to be truly ready to receive it.',
    metaModern: 'The Star holds the survivor\'s hard-won hope, the mystic\'s trust in cosmic benevolence, the strategist\'s regenerative vision, and the advocate\'s question about whose waters are whose—all flowing from her vessels simultaneously. Hope at its most mature is not naive but earned, tested, and poured deliberately. She shines because she has been through the dark and chosen to illuminate anyway.',
  },
  'Pisces': {
    majorArcana: 'The Moon',
    cardKey: 'moon',
    romanNumeral: 'XVIII',
    arcanaNumber: 18,
    title: 'Ruler of Flux and Reflux; Child of the Sons of the Mighty',
    description: 'The Moon represents the realm where reason dissolves and the deep unconscious speaks in image and symbol—the Jupiter/Neptune-ruled Pisces energy expressed as the threshold between worlds. The crayfish emerges from the primordial waters; the wolf and the dog howl at what they cannot comprehend; two towers mark the boundary of the known. The path between them leads into the unknowable beyond.',
    jungian: 'The Moon represents the deepest layer of the collective unconscious—the primordial, pre-logical realm from which both the most numinous and the most disturbing contents arise. She is the night sea journey, the place where the hero must navigate without the sun\'s certainty. Her light is reflected, not original—illuminating just enough of the unconscious to walk through, never enough to eliminate the unknown.',
    powerGods: 'In the dark, you have the advantage. Others need daylight to find their way; you have learned to navigate by the Moon\'s uncertain light, to read the messages of the waters, to follow the path that only shows itself step by step. This is the deepest strategic advantage: comfort with the unknown that makes you effective where others freeze with fear.',
    traditional: 'The Moon is the realm of sacred mystery—the domain where the veil between worlds grows thin and the ancestors walk close. The traditions of dream interpretation, oracle, and vision all arise from this liminal space. Navigate with prayer and protection; not all that moves in the Moon\'s light is benevolent. The path between the towers is real, but it requires guidance from above to walk safely.',
    modern: 'The Moon represents the unknown unknowns—the market forces not captured in the model, the user behaviors that confound the assumptions, the organizational dynamics hidden beneath the reported data. Comfort with ambiguity is a leadership competency. Not everything can be illuminated in advance; the skill is navigating effectively with incomplete information while remaining oriented toward the destination.',
    postModern: 'The Moon\'s light reveals different things to different eyes. The crayfish emerging from the water—what has lived in the depths, unseen and unnamed? The path between the towers is not universal; it runs through territories that mean different things to different travelers. Liminal spaces are beautiful and dangerous in unequal measure for different communities. Who is safe in the moonlit threshold?',
    metaModern: 'The Moon holds the navigator\'s comfort with darkness, the devotee\'s sacred mystery, the analyst\'s unknown unknowns, and the advocate\'s acknowledgment that the threshold is not neutral ground—all swirling in the reflected light. The deepest wisdom is not the elimination of uncertainty but the capacity to remain oriented within it, knowing that the path reveals itself step by step to those willing to walk without the guarantee of daylight.',
  },
};
